# coding: utf-8

# flake8: noqa

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.air_quality import AirQuality
from swagger_client.models.astro import Astro
from swagger_client.models.autocomplete_response import AutocompleteResponse
from swagger_client.models.autocomplete_response_request import AutocompleteResponseRequest
from swagger_client.models.autocomplete_result import AutocompleteResult
from swagger_client.models.current import Current
from swagger_client.models.current_air_quality import CurrentAirQuality
from swagger_client.models.current_astro import CurrentAstro
from swagger_client.models.current_weather_response import CurrentWeatherResponse
from swagger_client.models.current_weather_response_location import CurrentWeatherResponseLocation
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.error_response_error import ErrorResponseError
from swagger_client.models.forecast_day import ForecastDay
from swagger_client.models.forecast_day_air_quality import ForecastDayAirQuality
from swagger_client.models.forecast_day_astro import ForecastDayAstro
from swagger_client.models.forecast_response import ForecastResponse
from swagger_client.models.forecast_response_current import ForecastResponseCurrent
from swagger_client.models.forecast_response_forecast import ForecastResponseForecast
from swagger_client.models.forecast_response_location import ForecastResponseLocation
from swagger_client.models.forecast_response_request import ForecastResponseRequest
from swagger_client.models.historical_day import HistoricalDay
from swagger_client.models.historical_response import HistoricalResponse
from swagger_client.models.historical_response_historical import HistoricalResponseHistorical
from swagger_client.models.historical_response_location import HistoricalResponseLocation
from swagger_client.models.hourly_entry import HourlyEntry
from swagger_client.models.hourly_entry_air_quality import HourlyEntryAirQuality
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.inline_response2002 import InlineResponse2002
from swagger_client.models.inline_response2003 import InlineResponse2003
from swagger_client.models.inline_response2004 import InlineResponse2004
from swagger_client.models.inline_response2005 import InlineResponse2005
from swagger_client.models.inline_response4_xx import InlineResponse4XX
from swagger_client.models.location import Location
from swagger_client.models.marine_forecast_day import MarineForecastDay
from swagger_client.models.marine_hourly_entry import MarineHourlyEntry
from swagger_client.models.marine_response import MarineResponse
from swagger_client.models.marine_tide_entry import MarineTideEntry
from swagger_client.models.past_marine_response import PastMarineResponse
from swagger_client.models.past_marine_response_astro import PastMarineResponseAstro
from swagger_client.models.past_marine_response_historical import PastMarineResponseHistorical
from swagger_client.models.request_info import RequestInfo
from swagger_client.models.tide_entry import TideEntry
