# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def autocomplete_location(self, access_key, query, **kwargs):  # noqa: E501
        """Location Lookup/Autocomplete  # noqa: E501

        The Weatherstack API's Location Lookup/Autocomplete endpoint can be used to pinpoint one or more specific locations and their identifying response objects with the aim of later passing them to a weather data endpoint. In our example below, we are looking for London, United Kingdom.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.autocomplete_location(access_key, query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object query: Free-text location identifier. Examples: `New York`, `London, UK`, `51.5074,-0.1278`, `fetch:ip` (auto-detect by requester's IP). For bulk queries pass semicolon-separated locations (Professional and higher plans).  (required)
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.autocomplete_location_with_http_info(access_key, query, **kwargs)  # noqa: E501
        else:
            (data) = self.autocomplete_location_with_http_info(access_key, query, **kwargs)  # noqa: E501
            return data

    def autocomplete_location_with_http_info(self, access_key, query, **kwargs):  # noqa: E501
        """Location Lookup/Autocomplete  # noqa: E501

        The Weatherstack API's Location Lookup/Autocomplete endpoint can be used to pinpoint one or more specific locations and their identifying response objects with the aim of later passing them to a weather data endpoint. In our example below, we are looking for London, United Kingdom.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.autocomplete_location_with_http_info(access_key, query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object query: Free-text location identifier. Examples: `New York`, `London, UK`, `51.5074,-0.1278`, `fetch:ip` (auto-detect by requester's IP). For bulk queries pass semicolon-separated locations (Professional and higher plans).  (required)
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'query', 'param_callback']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method autocomplete_location" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `autocomplete_location`")  # noqa: E501
        # verify the required parameter 'query' is set
        if ('query' not in params or
                params['query'] is None):
            raise ValueError("Missing the required parameter `query` when calling `autocomplete_location`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'query' in params:
            query_params.append(('query', params['query']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['WeatherstackKey']  # noqa: E501

        return self.api_client.call_api(
            '/autocomplete', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2005',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_current_weather(self, access_key, query, **kwargs):  # noqa: E501
        """Current Weather  # noqa: E501

        To query the Weatherstack API for real-time weather data in a location of your choice, simply attach your preferred location to the API's `current` endpoint as seen in the example request below. Depending on your subscription, you can also make a bulk location request by passing multiple semicolon-separated locations to the API URL.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_current_weather(access_key, query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object query: Free-text location identifier. Examples: `New York`, `London, UK`, `51.5074,-0.1278`, `fetch:ip` (auto-detect by requester's IP). For bulk queries pass semicolon-separated locations (Professional and higher plans).  (required)
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_current_weather_with_http_info(access_key, query, **kwargs)  # noqa: E501
        else:
            (data) = self.get_current_weather_with_http_info(access_key, query, **kwargs)  # noqa: E501
            return data

    def get_current_weather_with_http_info(self, access_key, query, **kwargs):  # noqa: E501
        """Current Weather  # noqa: E501

        To query the Weatherstack API for real-time weather data in a location of your choice, simply attach your preferred location to the API's `current` endpoint as seen in the example request below. Depending on your subscription, you can also make a bulk location request by passing multiple semicolon-separated locations to the API URL.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_current_weather_with_http_info(access_key, query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object query: Free-text location identifier. Examples: `New York`, `London, UK`, `51.5074,-0.1278`, `fetch:ip` (auto-detect by requester's IP). For bulk queries pass semicolon-separated locations (Professional and higher plans).  (required)
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'query', 'units', 'language', 'param_callback']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_current_weather" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_current_weather`")  # noqa: E501
        # verify the required parameter 'query' is set
        if ('query' not in params or
                params['query'] is None):
            raise ValueError("Missing the required parameter `query` when calling `get_current_weather`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'query' in params:
            query_params.append(('query', params['query']))  # noqa: E501
        if 'units' in params:
            query_params.append(('units', params['units']))  # noqa: E501
        if 'language' in params:
            query_params.append(('language', params['language']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['WeatherstackKey']  # noqa: E501

        return self.api_client.call_api(
            '/current', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse200',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_historical_marine_weather(self, access_key, latitude, longitude, historical_date_start, **kwargs):  # noqa: E501
        """Historical Marine Weather  # noqa: E501

        The Historical Marine Weather API have marine data since 1st Jan, 2015 for a given `latitude` and `longitude`, as well as tide data. This endpoint will return weather elements such as temperature, precipitation (rainfall), weather description, weather icon, wind speed, Tide data, significant wave height, swell height, swell direction and swell period.      **Note:** *Each day and location included in your request counts toward your monthly API request limit. The historical marine time series supports a maximum time frame of 35 days.*   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_historical_marine_weather(access_key, latitude, longitude, historical_date_start, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object latitude: Latitude coordinate (decimal degrees) for marine endpoints. (required)
        :param object longitude: Longitude coordinate (decimal degrees) for marine endpoints. (required)
        :param object historical_date_start: Start date for a historical time-series (required for time-series requests). (required)
        :param object historical_date_end: End date for a historical time-series request (maximum timeframe: 60 days).
        :param object tide: Set `tide=yes` to include tidal information (where available). Defaults to `no`.
        :param object hourly: Set to `1` to include hourly breakdown, or `0` (default) to omit hourly data.
        :param object interval: When `hourly=1`, defines the spacing of hourly entries: 1 (hourly), 3 (default), 6, 12, or 24 (day average). 
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2004
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_historical_marine_weather_with_http_info(access_key, latitude, longitude, historical_date_start, **kwargs)  # noqa: E501
        else:
            (data) = self.get_historical_marine_weather_with_http_info(access_key, latitude, longitude, historical_date_start, **kwargs)  # noqa: E501
            return data

    def get_historical_marine_weather_with_http_info(self, access_key, latitude, longitude, historical_date_start, **kwargs):  # noqa: E501
        """Historical Marine Weather  # noqa: E501

        The Historical Marine Weather API have marine data since 1st Jan, 2015 for a given `latitude` and `longitude`, as well as tide data. This endpoint will return weather elements such as temperature, precipitation (rainfall), weather description, weather icon, wind speed, Tide data, significant wave height, swell height, swell direction and swell period.      **Note:** *Each day and location included in your request counts toward your monthly API request limit. The historical marine time series supports a maximum time frame of 35 days.*   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_historical_marine_weather_with_http_info(access_key, latitude, longitude, historical_date_start, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object latitude: Latitude coordinate (decimal degrees) for marine endpoints. (required)
        :param object longitude: Longitude coordinate (decimal degrees) for marine endpoints. (required)
        :param object historical_date_start: Start date for a historical time-series (required for time-series requests). (required)
        :param object historical_date_end: End date for a historical time-series request (maximum timeframe: 60 days).
        :param object tide: Set `tide=yes` to include tidal information (where available). Defaults to `no`.
        :param object hourly: Set to `1` to include hourly breakdown, or `0` (default) to omit hourly data.
        :param object interval: When `hourly=1`, defines the spacing of hourly entries: 1 (hourly), 3 (default), 6, 12, or 24 (day average). 
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2004
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'latitude', 'longitude', 'historical_date_start', 'historical_date_end', 'tide', 'hourly', 'interval', 'units', 'language', 'param_callback']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_historical_marine_weather" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_historical_marine_weather`")  # noqa: E501
        # verify the required parameter 'latitude' is set
        if ('latitude' not in params or
                params['latitude'] is None):
            raise ValueError("Missing the required parameter `latitude` when calling `get_historical_marine_weather`")  # noqa: E501
        # verify the required parameter 'longitude' is set
        if ('longitude' not in params or
                params['longitude'] is None):
            raise ValueError("Missing the required parameter `longitude` when calling `get_historical_marine_weather`")  # noqa: E501
        # verify the required parameter 'historical_date_start' is set
        if ('historical_date_start' not in params or
                params['historical_date_start'] is None):
            raise ValueError("Missing the required parameter `historical_date_start` when calling `get_historical_marine_weather`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'latitude' in params:
            query_params.append(('latitude', params['latitude']))  # noqa: E501
        if 'longitude' in params:
            query_params.append(('longitude', params['longitude']))  # noqa: E501
        if 'historical_date_start' in params:
            query_params.append(('historical_date_start', params['historical_date_start']))  # noqa: E501
        if 'historical_date_end' in params:
            query_params.append(('historical_date_end', params['historical_date_end']))  # noqa: E501
        if 'tide' in params:
            query_params.append(('tide', params['tide']))  # noqa: E501
        if 'hourly' in params:
            query_params.append(('hourly', params['hourly']))  # noqa: E501
        if 'interval' in params:
            query_params.append(('interval', params['interval']))  # noqa: E501
        if 'units' in params:
            query_params.append(('units', params['units']))  # noqa: E501
        if 'language' in params:
            query_params.append(('language', params['language']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['WeatherstackKey']  # noqa: E501

        return self.api_client.call_api(
            '/past-marine', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2004',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_historical_weather(self, access_key, query, historical_date, **kwargs):  # noqa: E501
        """Historical Weather  # noqa: E501

        To look up historical weather data all the way back to 2015, simply pass one date of your choice (later than July 2008) or multiple semicolon-separated dates to the Weatherstack API's Historical Weather endpoint using the  `historical_date` parameter.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_historical_weather(access_key, query, historical_date, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object query: Free-text location identifier. Examples: `New York`, `London, UK`, `51.5074,-0.1278`, `fetch:ip` (auto-detect by requester's IP). For bulk queries pass semicolon-separated locations (Professional and higher plans).  (required)
        :param object historical_date: Single historical date (YYYY-MM-DD) or semicolon-separated list of dates. Used to request specific historical days (availability depends on subscription and archives).  (required)
        :param object historical_date_start: Start date for a historical time-series (required for time-series requests).
        :param object historical_date_end: End date for a historical time-series request (maximum timeframe: 60 days).
        :param object hourly: Set to `1` to include hourly breakdown, or `0` (default) to omit hourly data.
        :param object interval: When `hourly=1`, defines the spacing of hourly entries: 1 (hourly), 3 (default), 6, 12, or 24 (day average). 
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2002
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_historical_weather_with_http_info(access_key, query, historical_date, **kwargs)  # noqa: E501
        else:
            (data) = self.get_historical_weather_with_http_info(access_key, query, historical_date, **kwargs)  # noqa: E501
            return data

    def get_historical_weather_with_http_info(self, access_key, query, historical_date, **kwargs):  # noqa: E501
        """Historical Weather  # noqa: E501

        To look up historical weather data all the way back to 2015, simply pass one date of your choice (later than July 2008) or multiple semicolon-separated dates to the Weatherstack API's Historical Weather endpoint using the  `historical_date` parameter.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_historical_weather_with_http_info(access_key, query, historical_date, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object query: Free-text location identifier. Examples: `New York`, `London, UK`, `51.5074,-0.1278`, `fetch:ip` (auto-detect by requester's IP). For bulk queries pass semicolon-separated locations (Professional and higher plans).  (required)
        :param object historical_date: Single historical date (YYYY-MM-DD) or semicolon-separated list of dates. Used to request specific historical days (availability depends on subscription and archives).  (required)
        :param object historical_date_start: Start date for a historical time-series (required for time-series requests).
        :param object historical_date_end: End date for a historical time-series request (maximum timeframe: 60 days).
        :param object hourly: Set to `1` to include hourly breakdown, or `0` (default) to omit hourly data.
        :param object interval: When `hourly=1`, defines the spacing of hourly entries: 1 (hourly), 3 (default), 6, 12, or 24 (day average). 
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2002
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'query', 'historical_date', 'historical_date_start', 'historical_date_end', 'hourly', 'interval', 'units', 'language', 'param_callback']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_historical_weather" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_historical_weather`")  # noqa: E501
        # verify the required parameter 'query' is set
        if ('query' not in params or
                params['query'] is None):
            raise ValueError("Missing the required parameter `query` when calling `get_historical_weather`")  # noqa: E501
        # verify the required parameter 'historical_date' is set
        if ('historical_date' not in params or
                params['historical_date'] is None):
            raise ValueError("Missing the required parameter `historical_date` when calling `get_historical_weather`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'query' in params:
            query_params.append(('query', params['query']))  # noqa: E501
        if 'historical_date' in params:
            query_params.append(('historical_date', params['historical_date']))  # noqa: E501
        if 'historical_date_start' in params:
            query_params.append(('historical_date_start', params['historical_date_start']))  # noqa: E501
        if 'historical_date_end' in params:
            query_params.append(('historical_date_end', params['historical_date_end']))  # noqa: E501
        if 'hourly' in params:
            query_params.append(('hourly', params['hourly']))  # noqa: E501
        if 'interval' in params:
            query_params.append(('interval', params['interval']))  # noqa: E501
        if 'units' in params:
            query_params.append(('units', params['units']))  # noqa: E501
        if 'language' in params:
            query_params.append(('language', params['language']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['WeatherstackKey']  # noqa: E501

        return self.api_client.call_api(
            '/historical', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2002',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_marine_weather(self, access_key, latitude, longitude, **kwargs):  # noqa: E501
        """Marine Weather  # noqa: E501

        The Marine Weather API endpoint will allow to access today's live marine/sailing weather forecast for a given `longitude` and `latitude` , as well as up to 7 days of forecast.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_marine_weather(access_key, latitude, longitude, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object latitude: Latitude coordinate (decimal degrees) for marine endpoints. (required)
        :param object longitude: Longitude coordinate (decimal degrees) for marine endpoints. (required)
        :param object tide: Set `tide=yes` to include tidal information (where available). Defaults to `no`.
        :param object hourly: Set to `1` to include hourly breakdown, or `0` (default) to omit hourly data.
        :param object interval: When `hourly=1`, defines the spacing of hourly entries: 1 (hourly), 3 (default), 6, 12, or 24 (day average). 
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2003
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_marine_weather_with_http_info(access_key, latitude, longitude, **kwargs)  # noqa: E501
        else:
            (data) = self.get_marine_weather_with_http_info(access_key, latitude, longitude, **kwargs)  # noqa: E501
            return data

    def get_marine_weather_with_http_info(self, access_key, latitude, longitude, **kwargs):  # noqa: E501
        """Marine Weather  # noqa: E501

        The Marine Weather API endpoint will allow to access today's live marine/sailing weather forecast for a given `longitude` and `latitude` , as well as up to 7 days of forecast.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_marine_weather_with_http_info(access_key, latitude, longitude, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object latitude: Latitude coordinate (decimal degrees) for marine endpoints. (required)
        :param object longitude: Longitude coordinate (decimal degrees) for marine endpoints. (required)
        :param object tide: Set `tide=yes` to include tidal information (where available). Defaults to `no`.
        :param object hourly: Set to `1` to include hourly breakdown, or `0` (default) to omit hourly data.
        :param object interval: When `hourly=1`, defines the spacing of hourly entries: 1 (hourly), 3 (default), 6, 12, or 24 (day average). 
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2003
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'latitude', 'longitude', 'tide', 'hourly', 'interval', 'units', 'language', 'param_callback']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_marine_weather" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_marine_weather`")  # noqa: E501
        # verify the required parameter 'latitude' is set
        if ('latitude' not in params or
                params['latitude'] is None):
            raise ValueError("Missing the required parameter `latitude` when calling `get_marine_weather`")  # noqa: E501
        # verify the required parameter 'longitude' is set
        if ('longitude' not in params or
                params['longitude'] is None):
            raise ValueError("Missing the required parameter `longitude` when calling `get_marine_weather`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'latitude' in params:
            query_params.append(('latitude', params['latitude']))  # noqa: E501
        if 'longitude' in params:
            query_params.append(('longitude', params['longitude']))  # noqa: E501
        if 'tide' in params:
            query_params.append(('tide', params['tide']))  # noqa: E501
        if 'hourly' in params:
            query_params.append(('hourly', params['hourly']))  # noqa: E501
        if 'interval' in params:
            query_params.append(('interval', params['interval']))  # noqa: E501
        if 'units' in params:
            query_params.append(('units', params['units']))  # noqa: E501
        if 'language' in params:
            query_params.append(('language', params['language']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['WeatherstackKey']  # noqa: E501

        return self.api_client.call_api(
            '/marine', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2003',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_weather_forecast(self, access_key, query, **kwargs):  # noqa: E501
        """Weather Forecast  # noqa: E501

        The Weatherstack API is capable of returning weather forecast data for up to 14 days into the future. To get weather forecasts, simply use the API's Weather Forecast endpoint and define your preferred number of forecast days using the `forecast_days` parameter.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_weather_forecast(access_key, query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object query: Free-text location identifier. Examples: `New York`, `London, UK`, `51.5074,-0.1278`, `fetch:ip` (auto-detect by requester's IP). For bulk queries pass semicolon-separated locations (Professional and higher plans).  (required)
        :param object forecast_days: Number of days of forecast to return (depends on subscription; up to 14 days).
        :param object hourly: Set to `1` to include hourly breakdown, or `0` (default) to omit hourly data.
        :param object interval: When `hourly=1`, defines the spacing of hourly entries: 1 (hourly), 3 (default), 6, 12, or 24 (day average). 
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2001
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_weather_forecast_with_http_info(access_key, query, **kwargs)  # noqa: E501
        else:
            (data) = self.get_weather_forecast_with_http_info(access_key, query, **kwargs)  # noqa: E501
            return data

    def get_weather_forecast_with_http_info(self, access_key, query, **kwargs):  # noqa: E501
        """Weather Forecast  # noqa: E501

        The Weatherstack API is capable of returning weather forecast data for up to 14 days into the future. To get weather forecasts, simply use the API's Weather Forecast endpoint and define your preferred number of forecast days using the `forecast_days` parameter.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_weather_forecast_with_http_info(access_key, query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object access_key: Your Weatherstack API access key. Find it in your Weatherstack dashboard. (required)
        :param object query: Free-text location identifier. Examples: `New York`, `London, UK`, `51.5074,-0.1278`, `fetch:ip` (auto-detect by requester's IP). For bulk queries pass semicolon-separated locations (Professional and higher plans).  (required)
        :param object forecast_days: Number of days of forecast to return (depends on subscription; up to 14 days).
        :param object hourly: Set to `1` to include hourly breakdown, or `0` (default) to omit hourly data.
        :param object interval: When `hourly=1`, defines the spacing of hourly entries: 1 (hourly), 3 (default), 6, 12, or 24 (day average). 
        :param object units: Units system for returned values. `m` = Metric (default), `s` = Scientific, `f` = Fahrenheit. 
        :param object language: Optional ISO 2-letter language code to localize text fields (where supported).
        :param object param_callback: JSONP callback function name. When present, the API response is wrapped for JSONP.
        :return: InlineResponse2001
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'query', 'forecast_days', 'hourly', 'interval', 'units', 'language', 'param_callback']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_weather_forecast" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_weather_forecast`")  # noqa: E501
        # verify the required parameter 'query' is set
        if ('query' not in params or
                params['query'] is None):
            raise ValueError("Missing the required parameter `query` when calling `get_weather_forecast`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'query' in params:
            query_params.append(('query', params['query']))  # noqa: E501
        if 'forecast_days' in params:
            query_params.append(('forecast_days', params['forecast_days']))  # noqa: E501
        if 'hourly' in params:
            query_params.append(('hourly', params['hourly']))  # noqa: E501
        if 'interval' in params:
            query_params.append(('interval', params['interval']))  # noqa: E501
        if 'units' in params:
            query_params.append(('units', params['units']))  # noqa: E501
        if 'language' in params:
            query_params.append(('language', params['language']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['WeatherstackKey']  # noqa: E501

        return self.api_client.call_api(
            '/forecast', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2001',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
