# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Astro(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sunrise': 'object',
        'sunset': 'object',
        'moonrise': 'object',
        'moonset': 'object',
        'moon_phase': 'object',
        'moon_illumination': 'object'
    }

    attribute_map = {
        'sunrise': 'sunrise',
        'sunset': 'sunset',
        'moonrise': 'moonrise',
        'moonset': 'moonset',
        'moon_phase': 'moon_phase',
        'moon_illumination': 'moon_illumination'
    }

    def __init__(self, sunrise=None, sunset=None, moonrise=None, moonset=None, moon_phase=None, moon_illumination=None):  # noqa: E501
        """Astro - a model defined in Swagger"""  # noqa: E501
        self._sunrise = None
        self._sunset = None
        self._moonrise = None
        self._moonset = None
        self._moon_phase = None
        self._moon_illumination = None
        self.discriminator = None
        if sunrise is not None:
            self.sunrise = sunrise
        if sunset is not None:
            self.sunset = sunset
        if moonrise is not None:
            self.moonrise = moonrise
        if moonset is not None:
            self.moonset = moonset
        if moon_phase is not None:
            self.moon_phase = moon_phase
        if moon_illumination is not None:
            self.moon_illumination = moon_illumination

    @property
    def sunrise(self):
        """Gets the sunrise of this Astro.  # noqa: E501

        Time of sunrise at the location.  # noqa: E501

        :return: The sunrise of this Astro.  # noqa: E501
        :rtype: object
        """
        return self._sunrise

    @sunrise.setter
    def sunrise(self, sunrise):
        """Sets the sunrise of this Astro.

        Time of sunrise at the location.  # noqa: E501

        :param sunrise: The sunrise of this Astro.  # noqa: E501
        :type: object
        """

        self._sunrise = sunrise

    @property
    def sunset(self):
        """Gets the sunset of this Astro.  # noqa: E501

        Time of sunset at the location.  # noqa: E501

        :return: The sunset of this Astro.  # noqa: E501
        :rtype: object
        """
        return self._sunset

    @sunset.setter
    def sunset(self, sunset):
        """Sets the sunset of this Astro.

        Time of sunset at the location.  # noqa: E501

        :param sunset: The sunset of this Astro.  # noqa: E501
        :type: object
        """

        self._sunset = sunset

    @property
    def moonrise(self):
        """Gets the moonrise of this Astro.  # noqa: E501

        Time of moonrise at the location.  # noqa: E501

        :return: The moonrise of this Astro.  # noqa: E501
        :rtype: object
        """
        return self._moonrise

    @moonrise.setter
    def moonrise(self, moonrise):
        """Sets the moonrise of this Astro.

        Time of moonrise at the location.  # noqa: E501

        :param moonrise: The moonrise of this Astro.  # noqa: E501
        :type: object
        """

        self._moonrise = moonrise

    @property
    def moonset(self):
        """Gets the moonset of this Astro.  # noqa: E501

        Time of moonset at the location.  # noqa: E501

        :return: The moonset of this Astro.  # noqa: E501
        :rtype: object
        """
        return self._moonset

    @moonset.setter
    def moonset(self, moonset):
        """Sets the moonset of this Astro.

        Time of moonset at the location.  # noqa: E501

        :param moonset: The moonset of this Astro.  # noqa: E501
        :type: object
        """

        self._moonset = moonset

    @property
    def moon_phase(self):
        """Gets the moon_phase of this Astro.  # noqa: E501

        Current phase of the moon.  # noqa: E501

        :return: The moon_phase of this Astro.  # noqa: E501
        :rtype: object
        """
        return self._moon_phase

    @moon_phase.setter
    def moon_phase(self, moon_phase):
        """Sets the moon_phase of this Astro.

        Current phase of the moon.  # noqa: E501

        :param moon_phase: The moon_phase of this Astro.  # noqa: E501
        :type: object
        """

        self._moon_phase = moon_phase

    @property
    def moon_illumination(self):
        """Gets the moon_illumination of this Astro.  # noqa: E501

        Percentage of the moon illuminated.  # noqa: E501

        :return: The moon_illumination of this Astro.  # noqa: E501
        :rtype: object
        """
        return self._moon_illumination

    @moon_illumination.setter
    def moon_illumination(self, moon_illumination):
        """Sets the moon_illumination of this Astro.

        Percentage of the moon illuminated.  # noqa: E501

        :param moon_illumination: The moon_illumination of this Astro.  # noqa: E501
        :type: object
        """

        self._moon_illumination = moon_illumination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Astro, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Astro):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
