# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AutocompleteResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request': 'AutocompleteResponseRequest',
        'results': 'object'
    }

    attribute_map = {
        'request': 'request',
        'results': 'results'
    }

    def __init__(self, request=None, results=None):  # noqa: E501
        """AutocompleteResponse - a model defined in Swagger"""  # noqa: E501
        self._request = None
        self._results = None
        self.discriminator = None
        if request is not None:
            self.request = request
        if results is not None:
            self.results = results

    @property
    def request(self):
        """Gets the request of this AutocompleteResponse.  # noqa: E501


        :return: The request of this AutocompleteResponse.  # noqa: E501
        :rtype: AutocompleteResponseRequest
        """
        return self._request

    @request.setter
    def request(self, request):
        """Sets the request of this AutocompleteResponse.


        :param request: The request of this AutocompleteResponse.  # noqa: E501
        :type: AutocompleteResponseRequest
        """

        self._request = request

    @property
    def results(self):
        """Gets the results of this AutocompleteResponse.  # noqa: E501

        List of matching location suggestions.  # noqa: E501

        :return: The results of this AutocompleteResponse.  # noqa: E501
        :rtype: object
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this AutocompleteResponse.

        List of matching location suggestions.  # noqa: E501

        :param results: The results of this AutocompleteResponse.  # noqa: E501
        :type: object
        """

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AutocompleteResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AutocompleteResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
