# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CurrentAirQuality(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'co': 'object',
        'no2': 'object',
        'o3': 'object',
        'so2': 'object',
        'pm2_5': 'object',
        'pm10': 'object',
        'us_epa_index': 'object',
        'gb_defra_index': 'object'
    }

    attribute_map = {
        'co': 'co',
        'no2': 'no2',
        'o3': 'o3',
        'so2': 'so2',
        'pm2_5': 'pm2_5',
        'pm10': 'pm10',
        'us_epa_index': 'us-epa-index',
        'gb_defra_index': 'gb-defra-index'
    }

    def __init__(self, co=None, no2=None, o3=None, so2=None, pm2_5=None, pm10=None, us_epa_index=None, gb_defra_index=None):  # noqa: E501
        """CurrentAirQuality - a model defined in Swagger"""  # noqa: E501
        self._co = None
        self._no2 = None
        self._o3 = None
        self._so2 = None
        self._pm2_5 = None
        self._pm10 = None
        self._us_epa_index = None
        self._gb_defra_index = None
        self.discriminator = None
        if co is not None:
            self.co = co
        if no2 is not None:
            self.no2 = no2
        if o3 is not None:
            self.o3 = o3
        if so2 is not None:
            self.so2 = so2
        if pm2_5 is not None:
            self.pm2_5 = pm2_5
        if pm10 is not None:
            self.pm10 = pm10
        if us_epa_index is not None:
            self.us_epa_index = us_epa_index
        if gb_defra_index is not None:
            self.gb_defra_index = gb_defra_index

    @property
    def co(self):
        """Gets the co of this CurrentAirQuality.  # noqa: E501

        Carbon monoxide concentration.  # noqa: E501

        :return: The co of this CurrentAirQuality.  # noqa: E501
        :rtype: object
        """
        return self._co

    @co.setter
    def co(self, co):
        """Sets the co of this CurrentAirQuality.

        Carbon monoxide concentration.  # noqa: E501

        :param co: The co of this CurrentAirQuality.  # noqa: E501
        :type: object
        """

        self._co = co

    @property
    def no2(self):
        """Gets the no2 of this CurrentAirQuality.  # noqa: E501

        Nitrogen dioxide concentration.  # noqa: E501

        :return: The no2 of this CurrentAirQuality.  # noqa: E501
        :rtype: object
        """
        return self._no2

    @no2.setter
    def no2(self, no2):
        """Sets the no2 of this CurrentAirQuality.

        Nitrogen dioxide concentration.  # noqa: E501

        :param no2: The no2 of this CurrentAirQuality.  # noqa: E501
        :type: object
        """

        self._no2 = no2

    @property
    def o3(self):
        """Gets the o3 of this CurrentAirQuality.  # noqa: E501

        Ozone concentration.  # noqa: E501

        :return: The o3 of this CurrentAirQuality.  # noqa: E501
        :rtype: object
        """
        return self._o3

    @o3.setter
    def o3(self, o3):
        """Sets the o3 of this CurrentAirQuality.

        Ozone concentration.  # noqa: E501

        :param o3: The o3 of this CurrentAirQuality.  # noqa: E501
        :type: object
        """

        self._o3 = o3

    @property
    def so2(self):
        """Gets the so2 of this CurrentAirQuality.  # noqa: E501

        Sulfur dioxide concentration.  # noqa: E501

        :return: The so2 of this CurrentAirQuality.  # noqa: E501
        :rtype: object
        """
        return self._so2

    @so2.setter
    def so2(self, so2):
        """Sets the so2 of this CurrentAirQuality.

        Sulfur dioxide concentration.  # noqa: E501

        :param so2: The so2 of this CurrentAirQuality.  # noqa: E501
        :type: object
        """

        self._so2 = so2

    @property
    def pm2_5(self):
        """Gets the pm2_5 of this CurrentAirQuality.  # noqa: E501

        Particulate matter less than 2.5 microns.  # noqa: E501

        :return: The pm2_5 of this CurrentAirQuality.  # noqa: E501
        :rtype: object
        """
        return self._pm2_5

    @pm2_5.setter
    def pm2_5(self, pm2_5):
        """Sets the pm2_5 of this CurrentAirQuality.

        Particulate matter less than 2.5 microns.  # noqa: E501

        :param pm2_5: The pm2_5 of this CurrentAirQuality.  # noqa: E501
        :type: object
        """

        self._pm2_5 = pm2_5

    @property
    def pm10(self):
        """Gets the pm10 of this CurrentAirQuality.  # noqa: E501

        Particulate matter less than 10 microns.  # noqa: E501

        :return: The pm10 of this CurrentAirQuality.  # noqa: E501
        :rtype: object
        """
        return self._pm10

    @pm10.setter
    def pm10(self, pm10):
        """Sets the pm10 of this CurrentAirQuality.

        Particulate matter less than 10 microns.  # noqa: E501

        :param pm10: The pm10 of this CurrentAirQuality.  # noqa: E501
        :type: object
        """

        self._pm10 = pm10

    @property
    def us_epa_index(self):
        """Gets the us_epa_index of this CurrentAirQuality.  # noqa: E501

        US EPA air quality index.  # noqa: E501

        :return: The us_epa_index of this CurrentAirQuality.  # noqa: E501
        :rtype: object
        """
        return self._us_epa_index

    @us_epa_index.setter
    def us_epa_index(self, us_epa_index):
        """Sets the us_epa_index of this CurrentAirQuality.

        US EPA air quality index.  # noqa: E501

        :param us_epa_index: The us_epa_index of this CurrentAirQuality.  # noqa: E501
        :type: object
        """

        self._us_epa_index = us_epa_index

    @property
    def gb_defra_index(self):
        """Gets the gb_defra_index of this CurrentAirQuality.  # noqa: E501

        UK DEFRA air quality index.  # noqa: E501

        :return: The gb_defra_index of this CurrentAirQuality.  # noqa: E501
        :rtype: object
        """
        return self._gb_defra_index

    @gb_defra_index.setter
    def gb_defra_index(self, gb_defra_index):
        """Sets the gb_defra_index of this CurrentAirQuality.

        UK DEFRA air quality index.  # noqa: E501

        :param gb_defra_index: The gb_defra_index of this CurrentAirQuality.  # noqa: E501
        :type: object
        """

        self._gb_defra_index = gb_defra_index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CurrentAirQuality, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CurrentAirQuality):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
