# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Current(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'observation_time': 'object',
        'temperature': 'object',
        'weather_code': 'object',
        'weather_icons': 'object',
        'weather_descriptions': 'object',
        'astro': 'CurrentAstro',
        'air_quality': 'CurrentAirQuality',
        'wind_speed': 'object',
        'wind_degree': 'object',
        'wind_dir': 'object',
        'pressure': 'object',
        'precip': 'object',
        'humidity': 'object',
        'cloudcover': 'object',
        'feelslike': 'object',
        'uv_index': 'object',
        'visibility': 'object'
    }

    attribute_map = {
        'observation_time': 'observation_time',
        'temperature': 'temperature',
        'weather_code': 'weather_code',
        'weather_icons': 'weather_icons',
        'weather_descriptions': 'weather_descriptions',
        'astro': 'astro',
        'air_quality': 'air_quality',
        'wind_speed': 'wind_speed',
        'wind_degree': 'wind_degree',
        'wind_dir': 'wind_dir',
        'pressure': 'pressure',
        'precip': 'precip',
        'humidity': 'humidity',
        'cloudcover': 'cloudcover',
        'feelslike': 'feelslike',
        'uv_index': 'uv_index',
        'visibility': 'visibility'
    }

    def __init__(self, observation_time=None, temperature=None, weather_code=None, weather_icons=None, weather_descriptions=None, astro=None, air_quality=None, wind_speed=None, wind_degree=None, wind_dir=None, pressure=None, precip=None, humidity=None, cloudcover=None, feelslike=None, uv_index=None, visibility=None):  # noqa: E501
        """Current - a model defined in Swagger"""  # noqa: E501
        self._observation_time = None
        self._temperature = None
        self._weather_code = None
        self._weather_icons = None
        self._weather_descriptions = None
        self._astro = None
        self._air_quality = None
        self._wind_speed = None
        self._wind_degree = None
        self._wind_dir = None
        self._pressure = None
        self._precip = None
        self._humidity = None
        self._cloudcover = None
        self._feelslike = None
        self._uv_index = None
        self._visibility = None
        self.discriminator = None
        if observation_time is not None:
            self.observation_time = observation_time
        if temperature is not None:
            self.temperature = temperature
        if weather_code is not None:
            self.weather_code = weather_code
        if weather_icons is not None:
            self.weather_icons = weather_icons
        if weather_descriptions is not None:
            self.weather_descriptions = weather_descriptions
        if astro is not None:
            self.astro = astro
        if air_quality is not None:
            self.air_quality = air_quality
        if wind_speed is not None:
            self.wind_speed = wind_speed
        if wind_degree is not None:
            self.wind_degree = wind_degree
        if wind_dir is not None:
            self.wind_dir = wind_dir
        if pressure is not None:
            self.pressure = pressure
        if precip is not None:
            self.precip = precip
        if humidity is not None:
            self.humidity = humidity
        if cloudcover is not None:
            self.cloudcover = cloudcover
        if feelslike is not None:
            self.feelslike = feelslike
        if uv_index is not None:
            self.uv_index = uv_index
        if visibility is not None:
            self.visibility = visibility

    @property
    def observation_time(self):
        """Gets the observation_time of this Current.  # noqa: E501

        Time of the weather observation.  # noqa: E501

        :return: The observation_time of this Current.  # noqa: E501
        :rtype: object
        """
        return self._observation_time

    @observation_time.setter
    def observation_time(self, observation_time):
        """Sets the observation_time of this Current.

        Time of the weather observation.  # noqa: E501

        :param observation_time: The observation_time of this Current.  # noqa: E501
        :type: object
        """

        self._observation_time = observation_time

    @property
    def temperature(self):
        """Gets the temperature of this Current.  # noqa: E501

        Current temperature at the location.  # noqa: E501

        :return: The temperature of this Current.  # noqa: E501
        :rtype: object
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this Current.

        Current temperature at the location.  # noqa: E501

        :param temperature: The temperature of this Current.  # noqa: E501
        :type: object
        """

        self._temperature = temperature

    @property
    def weather_code(self):
        """Gets the weather_code of this Current.  # noqa: E501

        Weather condition code.  # noqa: E501

        :return: The weather_code of this Current.  # noqa: E501
        :rtype: object
        """
        return self._weather_code

    @weather_code.setter
    def weather_code(self, weather_code):
        """Sets the weather_code of this Current.

        Weather condition code.  # noqa: E501

        :param weather_code: The weather_code of this Current.  # noqa: E501
        :type: object
        """

        self._weather_code = weather_code

    @property
    def weather_icons(self):
        """Gets the weather_icons of this Current.  # noqa: E501

        Array of icon URLs representing the weather.  # noqa: E501

        :return: The weather_icons of this Current.  # noqa: E501
        :rtype: object
        """
        return self._weather_icons

    @weather_icons.setter
    def weather_icons(self, weather_icons):
        """Sets the weather_icons of this Current.

        Array of icon URLs representing the weather.  # noqa: E501

        :param weather_icons: The weather_icons of this Current.  # noqa: E501
        :type: object
        """

        self._weather_icons = weather_icons

    @property
    def weather_descriptions(self):
        """Gets the weather_descriptions of this Current.  # noqa: E501

        Array of text descriptions of the weather.  # noqa: E501

        :return: The weather_descriptions of this Current.  # noqa: E501
        :rtype: object
        """
        return self._weather_descriptions

    @weather_descriptions.setter
    def weather_descriptions(self, weather_descriptions):
        """Sets the weather_descriptions of this Current.

        Array of text descriptions of the weather.  # noqa: E501

        :param weather_descriptions: The weather_descriptions of this Current.  # noqa: E501
        :type: object
        """

        self._weather_descriptions = weather_descriptions

    @property
    def astro(self):
        """Gets the astro of this Current.  # noqa: E501


        :return: The astro of this Current.  # noqa: E501
        :rtype: CurrentAstro
        """
        return self._astro

    @astro.setter
    def astro(self, astro):
        """Sets the astro of this Current.


        :param astro: The astro of this Current.  # noqa: E501
        :type: CurrentAstro
        """

        self._astro = astro

    @property
    def air_quality(self):
        """Gets the air_quality of this Current.  # noqa: E501


        :return: The air_quality of this Current.  # noqa: E501
        :rtype: CurrentAirQuality
        """
        return self._air_quality

    @air_quality.setter
    def air_quality(self, air_quality):
        """Sets the air_quality of this Current.


        :param air_quality: The air_quality of this Current.  # noqa: E501
        :type: CurrentAirQuality
        """

        self._air_quality = air_quality

    @property
    def wind_speed(self):
        """Gets the wind_speed of this Current.  # noqa: E501

        Current wind speed.  # noqa: E501

        :return: The wind_speed of this Current.  # noqa: E501
        :rtype: object
        """
        return self._wind_speed

    @wind_speed.setter
    def wind_speed(self, wind_speed):
        """Sets the wind_speed of this Current.

        Current wind speed.  # noqa: E501

        :param wind_speed: The wind_speed of this Current.  # noqa: E501
        :type: object
        """

        self._wind_speed = wind_speed

    @property
    def wind_degree(self):
        """Gets the wind_degree of this Current.  # noqa: E501

        Wind direction in degrees.  # noqa: E501

        :return: The wind_degree of this Current.  # noqa: E501
        :rtype: object
        """
        return self._wind_degree

    @wind_degree.setter
    def wind_degree(self, wind_degree):
        """Sets the wind_degree of this Current.

        Wind direction in degrees.  # noqa: E501

        :param wind_degree: The wind_degree of this Current.  # noqa: E501
        :type: object
        """

        self._wind_degree = wind_degree

    @property
    def wind_dir(self):
        """Gets the wind_dir of this Current.  # noqa: E501

        Wind direction as a compass point.  # noqa: E501

        :return: The wind_dir of this Current.  # noqa: E501
        :rtype: object
        """
        return self._wind_dir

    @wind_dir.setter
    def wind_dir(self, wind_dir):
        """Sets the wind_dir of this Current.

        Wind direction as a compass point.  # noqa: E501

        :param wind_dir: The wind_dir of this Current.  # noqa: E501
        :type: object
        """

        self._wind_dir = wind_dir

    @property
    def pressure(self):
        """Gets the pressure of this Current.  # noqa: E501

        Atmospheric pressure.  # noqa: E501

        :return: The pressure of this Current.  # noqa: E501
        :rtype: object
        """
        return self._pressure

    @pressure.setter
    def pressure(self, pressure):
        """Sets the pressure of this Current.

        Atmospheric pressure.  # noqa: E501

        :param pressure: The pressure of this Current.  # noqa: E501
        :type: object
        """

        self._pressure = pressure

    @property
    def precip(self):
        """Gets the precip of this Current.  # noqa: E501

        Precipitation amount.  # noqa: E501

        :return: The precip of this Current.  # noqa: E501
        :rtype: object
        """
        return self._precip

    @precip.setter
    def precip(self, precip):
        """Sets the precip of this Current.

        Precipitation amount.  # noqa: E501

        :param precip: The precip of this Current.  # noqa: E501
        :type: object
        """

        self._precip = precip

    @property
    def humidity(self):
        """Gets the humidity of this Current.  # noqa: E501

        Relative humidity percentage.  # noqa: E501

        :return: The humidity of this Current.  # noqa: E501
        :rtype: object
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity):
        """Sets the humidity of this Current.

        Relative humidity percentage.  # noqa: E501

        :param humidity: The humidity of this Current.  # noqa: E501
        :type: object
        """

        self._humidity = humidity

    @property
    def cloudcover(self):
        """Gets the cloudcover of this Current.  # noqa: E501

        Cloud cover percentage.  # noqa: E501

        :return: The cloudcover of this Current.  # noqa: E501
        :rtype: object
        """
        return self._cloudcover

    @cloudcover.setter
    def cloudcover(self, cloudcover):
        """Sets the cloudcover of this Current.

        Cloud cover percentage.  # noqa: E501

        :param cloudcover: The cloudcover of this Current.  # noqa: E501
        :type: object
        """

        self._cloudcover = cloudcover

    @property
    def feelslike(self):
        """Gets the feelslike of this Current.  # noqa: E501

        Apparent temperature (feels like).  # noqa: E501

        :return: The feelslike of this Current.  # noqa: E501
        :rtype: object
        """
        return self._feelslike

    @feelslike.setter
    def feelslike(self, feelslike):
        """Sets the feelslike of this Current.

        Apparent temperature (feels like).  # noqa: E501

        :param feelslike: The feelslike of this Current.  # noqa: E501
        :type: object
        """

        self._feelslike = feelslike

    @property
    def uv_index(self):
        """Gets the uv_index of this Current.  # noqa: E501

        UV index value.  # noqa: E501

        :return: The uv_index of this Current.  # noqa: E501
        :rtype: object
        """
        return self._uv_index

    @uv_index.setter
    def uv_index(self, uv_index):
        """Sets the uv_index of this Current.

        UV index value.  # noqa: E501

        :param uv_index: The uv_index of this Current.  # noqa: E501
        :type: object
        """

        self._uv_index = uv_index

    @property
    def visibility(self):
        """Gets the visibility of this Current.  # noqa: E501

        Visibility distance.  # noqa: E501

        :return: The visibility of this Current.  # noqa: E501
        :rtype: object
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility):
        """Sets the visibility of this Current.

        Visibility distance.  # noqa: E501

        :param visibility: The visibility of this Current.  # noqa: E501
        :type: object
        """

        self._visibility = visibility

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Current, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Current):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
