# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ErrorResponseError(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'object',
        'type': 'object',
        'info': 'object'
    }

    attribute_map = {
        'code': 'code',
        'type': 'type',
        'info': 'info'
    }

    def __init__(self, code=None, type=None, info=None):  # noqa: E501
        """ErrorResponseError - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._type = None
        self._info = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if type is not None:
            self.type = type
        if info is not None:
            self.info = info

    @property
    def code(self):
        """Gets the code of this ErrorResponseError.  # noqa: E501

        Numeric error code.  # noqa: E501

        :return: The code of this ErrorResponseError.  # noqa: E501
        :rtype: object
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorResponseError.

        Numeric error code.  # noqa: E501

        :param code: The code of this ErrorResponseError.  # noqa: E501
        :type: object
        """

        self._code = code

    @property
    def type(self):
        """Gets the type of this ErrorResponseError.  # noqa: E501

        Error short identifier (e.g. unauthorized, missing_query).  # noqa: E501

        :return: The type of this ErrorResponseError.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ErrorResponseError.

        Error short identifier (e.g. unauthorized, missing_query).  # noqa: E501

        :param type: The type of this ErrorResponseError.  # noqa: E501
        :type: object
        """

        self._type = type

    @property
    def info(self):
        """Gets the info of this ErrorResponseError.  # noqa: E501

        Human-readable error message with guidance.  # noqa: E501

        :return: The info of this ErrorResponseError.  # noqa: E501
        :rtype: object
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this ErrorResponseError.

        Human-readable error message with guidance.  # noqa: E501

        :param info: The info of this ErrorResponseError.  # noqa: E501
        :type: object
        """

        self._info = info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ErrorResponseError, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorResponseError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
