# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ForecastResponseRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'object',
        'query': 'object',
        'language': 'object',
        'unit': 'object'
    }

    attribute_map = {
        'type': 'type',
        'query': 'query',
        'language': 'language',
        'unit': 'unit'
    }

    def __init__(self, type=None, query=None, language=None, unit=None):  # noqa: E501
        """ForecastResponseRequest - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._query = None
        self._language = None
        self._unit = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if query is not None:
            self.query = query
        if language is not None:
            self.language = language
        if unit is not None:
            self.unit = unit

    @property
    def type(self):
        """Gets the type of this ForecastResponseRequest.  # noqa: E501

        Type of location lookup performed (e.g., City, LatLon, IP, Zipcode).  # noqa: E501

        :return: The type of this ForecastResponseRequest.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ForecastResponseRequest.

        Type of location lookup performed (e.g., City, LatLon, IP, Zipcode).  # noqa: E501

        :param type: The type of this ForecastResponseRequest.  # noqa: E501
        :type: object
        """

        self._type = type

    @property
    def query(self):
        """Gets the query of this ForecastResponseRequest.  # noqa: E501

        The original location query string.  # noqa: E501

        :return: The query of this ForecastResponseRequest.  # noqa: E501
        :rtype: object
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this ForecastResponseRequest.

        The original location query string.  # noqa: E501

        :param query: The query of this ForecastResponseRequest.  # noqa: E501
        :type: object
        """

        self._query = query

    @property
    def language(self):
        """Gets the language of this ForecastResponseRequest.  # noqa: E501

        ISO 2-letter language code used for the response.  # noqa: E501

        :return: The language of this ForecastResponseRequest.  # noqa: E501
        :rtype: object
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this ForecastResponseRequest.

        ISO 2-letter language code used for the response.  # noqa: E501

        :param language: The language of this ForecastResponseRequest.  # noqa: E501
        :type: object
        """

        self._language = language

    @property
    def unit(self):
        """Gets the unit of this ForecastResponseRequest.  # noqa: E501

        Units system for returned values (m, s, or f).  # noqa: E501

        :return: The unit of this ForecastResponseRequest.  # noqa: E501
        :rtype: object
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this ForecastResponseRequest.

        Units system for returned values (m, s, or f).  # noqa: E501

        :param unit: The unit of this ForecastResponseRequest.  # noqa: E501
        :type: object
        """

        self._unit = unit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ForecastResponseRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ForecastResponseRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
