# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ForecastResponseLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'country': 'object',
        'region': 'object',
        'lat': 'object',
        'lon': 'object',
        'timezone_id': 'object',
        'localtime': 'object',
        'localtime_epoch': 'object',
        'utc_offset': 'object'
    }

    attribute_map = {
        'name': 'name',
        'country': 'country',
        'region': 'region',
        'lat': 'lat',
        'lon': 'lon',
        'timezone_id': 'timezone_id',
        'localtime': 'localtime',
        'localtime_epoch': 'localtime_epoch',
        'utc_offset': 'utc_offset'
    }

    def __init__(self, name=None, country=None, region=None, lat=None, lon=None, timezone_id=None, localtime=None, localtime_epoch=None, utc_offset=None):  # noqa: E501
        """ForecastResponseLocation - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._country = None
        self._region = None
        self._lat = None
        self._lon = None
        self._timezone_id = None
        self._localtime = None
        self._localtime_epoch = None
        self._utc_offset = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if country is not None:
            self.country = country
        if region is not None:
            self.region = region
        if lat is not None:
            self.lat = lat
        if lon is not None:
            self.lon = lon
        if timezone_id is not None:
            self.timezone_id = timezone_id
        if localtime is not None:
            self.localtime = localtime
        if localtime_epoch is not None:
            self.localtime_epoch = localtime_epoch
        if utc_offset is not None:
            self.utc_offset = utc_offset

    @property
    def name(self):
        """Gets the name of this ForecastResponseLocation.  # noqa: E501

        Name of the location (e.g., city or place).  # noqa: E501

        :return: The name of this ForecastResponseLocation.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ForecastResponseLocation.

        Name of the location (e.g., city or place).  # noqa: E501

        :param name: The name of this ForecastResponseLocation.  # noqa: E501
        :type: object
        """

        self._name = name

    @property
    def country(self):
        """Gets the country of this ForecastResponseLocation.  # noqa: E501

        Country where the location is situated.  # noqa: E501

        :return: The country of this ForecastResponseLocation.  # noqa: E501
        :rtype: object
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this ForecastResponseLocation.

        Country where the location is situated.  # noqa: E501

        :param country: The country of this ForecastResponseLocation.  # noqa: E501
        :type: object
        """

        self._country = country

    @property
    def region(self):
        """Gets the region of this ForecastResponseLocation.  # noqa: E501

        Region, state, or province of the location.  # noqa: E501

        :return: The region of this ForecastResponseLocation.  # noqa: E501
        :rtype: object
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this ForecastResponseLocation.

        Region, state, or province of the location.  # noqa: E501

        :param region: The region of this ForecastResponseLocation.  # noqa: E501
        :type: object
        """

        self._region = region

    @property
    def lat(self):
        """Gets the lat of this ForecastResponseLocation.  # noqa: E501

        Latitude coordinate of the location.  # noqa: E501

        :return: The lat of this ForecastResponseLocation.  # noqa: E501
        :rtype: object
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """Sets the lat of this ForecastResponseLocation.

        Latitude coordinate of the location.  # noqa: E501

        :param lat: The lat of this ForecastResponseLocation.  # noqa: E501
        :type: object
        """

        self._lat = lat

    @property
    def lon(self):
        """Gets the lon of this ForecastResponseLocation.  # noqa: E501

        Longitude coordinate of the location.  # noqa: E501

        :return: The lon of this ForecastResponseLocation.  # noqa: E501
        :rtype: object
        """
        return self._lon

    @lon.setter
    def lon(self, lon):
        """Sets the lon of this ForecastResponseLocation.

        Longitude coordinate of the location.  # noqa: E501

        :param lon: The lon of this ForecastResponseLocation.  # noqa: E501
        :type: object
        """

        self._lon = lon

    @property
    def timezone_id(self):
        """Gets the timezone_id of this ForecastResponseLocation.  # noqa: E501

        Time zone identifier for the location.  # noqa: E501

        :return: The timezone_id of this ForecastResponseLocation.  # noqa: E501
        :rtype: object
        """
        return self._timezone_id

    @timezone_id.setter
    def timezone_id(self, timezone_id):
        """Sets the timezone_id of this ForecastResponseLocation.

        Time zone identifier for the location.  # noqa: E501

        :param timezone_id: The timezone_id of this ForecastResponseLocation.  # noqa: E501
        :type: object
        """

        self._timezone_id = timezone_id

    @property
    def localtime(self):
        """Gets the localtime of this ForecastResponseLocation.  # noqa: E501

        Local date and time at the location.  # noqa: E501

        :return: The localtime of this ForecastResponseLocation.  # noqa: E501
        :rtype: object
        """
        return self._localtime

    @localtime.setter
    def localtime(self, localtime):
        """Sets the localtime of this ForecastResponseLocation.

        Local date and time at the location.  # noqa: E501

        :param localtime: The localtime of this ForecastResponseLocation.  # noqa: E501
        :type: object
        """

        self._localtime = localtime

    @property
    def localtime_epoch(self):
        """Gets the localtime_epoch of this ForecastResponseLocation.  # noqa: E501

        Local time as Unix epoch seconds.  # noqa: E501

        :return: The localtime_epoch of this ForecastResponseLocation.  # noqa: E501
        :rtype: object
        """
        return self._localtime_epoch

    @localtime_epoch.setter
    def localtime_epoch(self, localtime_epoch):
        """Sets the localtime_epoch of this ForecastResponseLocation.

        Local time as Unix epoch seconds.  # noqa: E501

        :param localtime_epoch: The localtime_epoch of this ForecastResponseLocation.  # noqa: E501
        :type: object
        """

        self._localtime_epoch = localtime_epoch

    @property
    def utc_offset(self):
        """Gets the utc_offset of this ForecastResponseLocation.  # noqa: E501

        Offset from UTC in hours for the location.  # noqa: E501

        :return: The utc_offset of this ForecastResponseLocation.  # noqa: E501
        :rtype: object
        """
        return self._utc_offset

    @utc_offset.setter
    def utc_offset(self, utc_offset):
        """Sets the utc_offset of this ForecastResponseLocation.

        Offset from UTC in hours for the location.  # noqa: E501

        :param utc_offset: The utc_offset of this ForecastResponseLocation.  # noqa: E501
        :type: object
        """

        self._utc_offset = utc_offset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ForecastResponseLocation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ForecastResponseLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
