# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HistoricalDay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'object',
        'date_epoch': 'object',
        'totalsnow': 'object',
        'sunhour': 'object',
        'uv_index': 'object',
        'hourly': 'object'
    }

    attribute_map = {
        '_date': 'date',
        'date_epoch': 'date_epoch',
        'totalsnow': 'totalsnow',
        'sunhour': 'sunhour',
        'uv_index': 'uv_index',
        'hourly': 'hourly'
    }

    def __init__(self, _date=None, date_epoch=None, totalsnow=None, sunhour=None, uv_index=None, hourly=None):  # noqa: E501
        """HistoricalDay - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._date_epoch = None
        self._totalsnow = None
        self._sunhour = None
        self._uv_index = None
        self._hourly = None
        self.discriminator = None
        if _date is not None:
            self._date = _date
        if date_epoch is not None:
            self.date_epoch = date_epoch
        if totalsnow is not None:
            self.totalsnow = totalsnow
        if sunhour is not None:
            self.sunhour = sunhour
        if uv_index is not None:
            self.uv_index = uv_index
        if hourly is not None:
            self.hourly = hourly

    @property
    def _date(self):
        """Gets the _date of this HistoricalDay.  # noqa: E501

        Historical date (YYYY-MM-DD).  # noqa: E501

        :return: The _date of this HistoricalDay.  # noqa: E501
        :rtype: object
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this HistoricalDay.

        Historical date (YYYY-MM-DD).  # noqa: E501

        :param _date: The _date of this HistoricalDay.  # noqa: E501
        :type: object
        """

        self.__date = _date

    @property
    def date_epoch(self):
        """Gets the date_epoch of this HistoricalDay.  # noqa: E501

        Historical date as Unix epoch seconds.  # noqa: E501

        :return: The date_epoch of this HistoricalDay.  # noqa: E501
        :rtype: object
        """
        return self._date_epoch

    @date_epoch.setter
    def date_epoch(self, date_epoch):
        """Sets the date_epoch of this HistoricalDay.

        Historical date as Unix epoch seconds.  # noqa: E501

        :param date_epoch: The date_epoch of this HistoricalDay.  # noqa: E501
        :type: object
        """

        self._date_epoch = date_epoch

    @property
    def totalsnow(self):
        """Gets the totalsnow of this HistoricalDay.  # noqa: E501

        Total snowfall for the day.  # noqa: E501

        :return: The totalsnow of this HistoricalDay.  # noqa: E501
        :rtype: object
        """
        return self._totalsnow

    @totalsnow.setter
    def totalsnow(self, totalsnow):
        """Sets the totalsnow of this HistoricalDay.

        Total snowfall for the day.  # noqa: E501

        :param totalsnow: The totalsnow of this HistoricalDay.  # noqa: E501
        :type: object
        """

        self._totalsnow = totalsnow

    @property
    def sunhour(self):
        """Gets the sunhour of this HistoricalDay.  # noqa: E501

        Total hours of sunshine for the day.  # noqa: E501

        :return: The sunhour of this HistoricalDay.  # noqa: E501
        :rtype: object
        """
        return self._sunhour

    @sunhour.setter
    def sunhour(self, sunhour):
        """Sets the sunhour of this HistoricalDay.

        Total hours of sunshine for the day.  # noqa: E501

        :param sunhour: The sunhour of this HistoricalDay.  # noqa: E501
        :type: object
        """

        self._sunhour = sunhour

    @property
    def uv_index(self):
        """Gets the uv_index of this HistoricalDay.  # noqa: E501

        UV index for the day.  # noqa: E501

        :return: The uv_index of this HistoricalDay.  # noqa: E501
        :rtype: object
        """
        return self._uv_index

    @uv_index.setter
    def uv_index(self, uv_index):
        """Sets the uv_index of this HistoricalDay.

        UV index for the day.  # noqa: E501

        :param uv_index: The uv_index of this HistoricalDay.  # noqa: E501
        :type: object
        """

        self._uv_index = uv_index

    @property
    def hourly(self):
        """Gets the hourly of this HistoricalDay.  # noqa: E501

        Hourly weather data entries for the day.  # noqa: E501

        :return: The hourly of this HistoricalDay.  # noqa: E501
        :rtype: object
        """
        return self._hourly

    @hourly.setter
    def hourly(self, hourly):
        """Sets the hourly of this HistoricalDay.

        Hourly weather data entries for the day.  # noqa: E501

        :param hourly: The hourly of this HistoricalDay.  # noqa: E501
        :type: object
        """

        self._hourly = hourly

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoricalDay, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoricalDay):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
