# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HourlyEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'object',
        'temperature': 'object',
        'weather_code': 'object',
        'weather_icons': 'object',
        'weather_descriptions': 'object',
        'precip': 'object',
        'humidity': 'object',
        'visibility': 'object',
        'pressure': 'object',
        'cloudcover': 'object',
        'heatindex': 'object',
        'dewpoint': 'object',
        'windchill': 'object',
        'windgust': 'object',
        'feelslike': 'object',
        'uv_index': 'object',
        'chanceofrain': 'object',
        'chanceofremdry': 'object',
        'chanceofwindy': 'object',
        'chanceofovercast': 'object',
        'chanceofsunshine': 'object',
        'chanceoffrost': 'object',
        'chanceofhightemp': 'object',
        'chanceoffog': 'object',
        'chanceofsnow': 'object',
        'chanceofthunder': 'object',
        'air_quality': 'HourlyEntryAirQuality'
    }

    attribute_map = {
        'time': 'time',
        'temperature': 'temperature',
        'weather_code': 'weather_code',
        'weather_icons': 'weather_icons',
        'weather_descriptions': 'weather_descriptions',
        'precip': 'precip',
        'humidity': 'humidity',
        'visibility': 'visibility',
        'pressure': 'pressure',
        'cloudcover': 'cloudcover',
        'heatindex': 'heatindex',
        'dewpoint': 'dewpoint',
        'windchill': 'windchill',
        'windgust': 'windgust',
        'feelslike': 'feelslike',
        'uv_index': 'uv_index',
        'chanceofrain': 'chanceofrain',
        'chanceofremdry': 'chanceofremdry',
        'chanceofwindy': 'chanceofwindy',
        'chanceofovercast': 'chanceofovercast',
        'chanceofsunshine': 'chanceofsunshine',
        'chanceoffrost': 'chanceoffrost',
        'chanceofhightemp': 'chanceofhightemp',
        'chanceoffog': 'chanceoffog',
        'chanceofsnow': 'chanceofsnow',
        'chanceofthunder': 'chanceofthunder',
        'air_quality': 'air_quality'
    }

    def __init__(self, time=None, temperature=None, weather_code=None, weather_icons=None, weather_descriptions=None, precip=None, humidity=None, visibility=None, pressure=None, cloudcover=None, heatindex=None, dewpoint=None, windchill=None, windgust=None, feelslike=None, uv_index=None, chanceofrain=None, chanceofremdry=None, chanceofwindy=None, chanceofovercast=None, chanceofsunshine=None, chanceoffrost=None, chanceofhightemp=None, chanceoffog=None, chanceofsnow=None, chanceofthunder=None, air_quality=None):  # noqa: E501
        """HourlyEntry - a model defined in Swagger"""  # noqa: E501
        self._time = None
        self._temperature = None
        self._weather_code = None
        self._weather_icons = None
        self._weather_descriptions = None
        self._precip = None
        self._humidity = None
        self._visibility = None
        self._pressure = None
        self._cloudcover = None
        self._heatindex = None
        self._dewpoint = None
        self._windchill = None
        self._windgust = None
        self._feelslike = None
        self._uv_index = None
        self._chanceofrain = None
        self._chanceofremdry = None
        self._chanceofwindy = None
        self._chanceofovercast = None
        self._chanceofsunshine = None
        self._chanceoffrost = None
        self._chanceofhightemp = None
        self._chanceoffog = None
        self._chanceofsnow = None
        self._chanceofthunder = None
        self._air_quality = None
        self.discriminator = None
        if time is not None:
            self.time = time
        if temperature is not None:
            self.temperature = temperature
        if weather_code is not None:
            self.weather_code = weather_code
        if weather_icons is not None:
            self.weather_icons = weather_icons
        if weather_descriptions is not None:
            self.weather_descriptions = weather_descriptions
        if precip is not None:
            self.precip = precip
        if humidity is not None:
            self.humidity = humidity
        if visibility is not None:
            self.visibility = visibility
        if pressure is not None:
            self.pressure = pressure
        if cloudcover is not None:
            self.cloudcover = cloudcover
        if heatindex is not None:
            self.heatindex = heatindex
        if dewpoint is not None:
            self.dewpoint = dewpoint
        if windchill is not None:
            self.windchill = windchill
        if windgust is not None:
            self.windgust = windgust
        if feelslike is not None:
            self.feelslike = feelslike
        if uv_index is not None:
            self.uv_index = uv_index
        if chanceofrain is not None:
            self.chanceofrain = chanceofrain
        if chanceofremdry is not None:
            self.chanceofremdry = chanceofremdry
        if chanceofwindy is not None:
            self.chanceofwindy = chanceofwindy
        if chanceofovercast is not None:
            self.chanceofovercast = chanceofovercast
        if chanceofsunshine is not None:
            self.chanceofsunshine = chanceofsunshine
        if chanceoffrost is not None:
            self.chanceoffrost = chanceoffrost
        if chanceofhightemp is not None:
            self.chanceofhightemp = chanceofhightemp
        if chanceoffog is not None:
            self.chanceoffog = chanceoffog
        if chanceofsnow is not None:
            self.chanceofsnow = chanceofsnow
        if chanceofthunder is not None:
            self.chanceofthunder = chanceofthunder
        if air_quality is not None:
            self.air_quality = air_quality

    @property
    def time(self):
        """Gets the time of this HourlyEntry.  # noqa: E501

        Time in 24h format (e.g. \"0900\" for 09:00).  # noqa: E501

        :return: The time of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this HourlyEntry.

        Time in 24h format (e.g. \"0900\" for 09:00).  # noqa: E501

        :param time: The time of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._time = time

    @property
    def temperature(self):
        """Gets the temperature of this HourlyEntry.  # noqa: E501

        Temperature at the given hour.  # noqa: E501

        :return: The temperature of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this HourlyEntry.

        Temperature at the given hour.  # noqa: E501

        :param temperature: The temperature of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._temperature = temperature

    @property
    def weather_code(self):
        """Gets the weather_code of this HourlyEntry.  # noqa: E501

        Weather condition code for the hour.  # noqa: E501

        :return: The weather_code of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._weather_code

    @weather_code.setter
    def weather_code(self, weather_code):
        """Sets the weather_code of this HourlyEntry.

        Weather condition code for the hour.  # noqa: E501

        :param weather_code: The weather_code of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._weather_code = weather_code

    @property
    def weather_icons(self):
        """Gets the weather_icons of this HourlyEntry.  # noqa: E501

        Array of icon URLs representing the weather.  # noqa: E501

        :return: The weather_icons of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._weather_icons

    @weather_icons.setter
    def weather_icons(self, weather_icons):
        """Sets the weather_icons of this HourlyEntry.

        Array of icon URLs representing the weather.  # noqa: E501

        :param weather_icons: The weather_icons of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._weather_icons = weather_icons

    @property
    def weather_descriptions(self):
        """Gets the weather_descriptions of this HourlyEntry.  # noqa: E501

        Array of text descriptions of the weather.  # noqa: E501

        :return: The weather_descriptions of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._weather_descriptions

    @weather_descriptions.setter
    def weather_descriptions(self, weather_descriptions):
        """Sets the weather_descriptions of this HourlyEntry.

        Array of text descriptions of the weather.  # noqa: E501

        :param weather_descriptions: The weather_descriptions of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._weather_descriptions = weather_descriptions

    @property
    def precip(self):
        """Gets the precip of this HourlyEntry.  # noqa: E501

        Precipitation amount for the hour.  # noqa: E501

        :return: The precip of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._precip

    @precip.setter
    def precip(self, precip):
        """Sets the precip of this HourlyEntry.

        Precipitation amount for the hour.  # noqa: E501

        :param precip: The precip of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._precip = precip

    @property
    def humidity(self):
        """Gets the humidity of this HourlyEntry.  # noqa: E501

        Relative humidity percentage.  # noqa: E501

        :return: The humidity of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity):
        """Sets the humidity of this HourlyEntry.

        Relative humidity percentage.  # noqa: E501

        :param humidity: The humidity of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._humidity = humidity

    @property
    def visibility(self):
        """Gets the visibility of this HourlyEntry.  # noqa: E501

        Visibility distance for the hour.  # noqa: E501

        :return: The visibility of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility):
        """Sets the visibility of this HourlyEntry.

        Visibility distance for the hour.  # noqa: E501

        :param visibility: The visibility of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._visibility = visibility

    @property
    def pressure(self):
        """Gets the pressure of this HourlyEntry.  # noqa: E501

        Atmospheric pressure for the hour.  # noqa: E501

        :return: The pressure of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._pressure

    @pressure.setter
    def pressure(self, pressure):
        """Sets the pressure of this HourlyEntry.

        Atmospheric pressure for the hour.  # noqa: E501

        :param pressure: The pressure of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._pressure = pressure

    @property
    def cloudcover(self):
        """Gets the cloudcover of this HourlyEntry.  # noqa: E501

        Cloud cover percentage.  # noqa: E501

        :return: The cloudcover of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._cloudcover

    @cloudcover.setter
    def cloudcover(self, cloudcover):
        """Sets the cloudcover of this HourlyEntry.

        Cloud cover percentage.  # noqa: E501

        :param cloudcover: The cloudcover of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._cloudcover = cloudcover

    @property
    def heatindex(self):
        """Gets the heatindex of this HourlyEntry.  # noqa: E501

        Heat index value for the hour.  # noqa: E501

        :return: The heatindex of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._heatindex

    @heatindex.setter
    def heatindex(self, heatindex):
        """Sets the heatindex of this HourlyEntry.

        Heat index value for the hour.  # noqa: E501

        :param heatindex: The heatindex of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._heatindex = heatindex

    @property
    def dewpoint(self):
        """Gets the dewpoint of this HourlyEntry.  # noqa: E501

        Dew point temperature for the hour.  # noqa: E501

        :return: The dewpoint of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._dewpoint

    @dewpoint.setter
    def dewpoint(self, dewpoint):
        """Sets the dewpoint of this HourlyEntry.

        Dew point temperature for the hour.  # noqa: E501

        :param dewpoint: The dewpoint of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._dewpoint = dewpoint

    @property
    def windchill(self):
        """Gets the windchill of this HourlyEntry.  # noqa: E501

        Wind chill temperature for the hour.  # noqa: E501

        :return: The windchill of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._windchill

    @windchill.setter
    def windchill(self, windchill):
        """Sets the windchill of this HourlyEntry.

        Wind chill temperature for the hour.  # noqa: E501

        :param windchill: The windchill of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._windchill = windchill

    @property
    def windgust(self):
        """Gets the windgust of this HourlyEntry.  # noqa: E501

        Wind gust speed for the hour.  # noqa: E501

        :return: The windgust of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._windgust

    @windgust.setter
    def windgust(self, windgust):
        """Sets the windgust of this HourlyEntry.

        Wind gust speed for the hour.  # noqa: E501

        :param windgust: The windgust of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._windgust = windgust

    @property
    def feelslike(self):
        """Gets the feelslike of this HourlyEntry.  # noqa: E501

        Apparent temperature (feels like) for the hour.  # noqa: E501

        :return: The feelslike of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._feelslike

    @feelslike.setter
    def feelslike(self, feelslike):
        """Sets the feelslike of this HourlyEntry.

        Apparent temperature (feels like) for the hour.  # noqa: E501

        :param feelslike: The feelslike of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._feelslike = feelslike

    @property
    def uv_index(self):
        """Gets the uv_index of this HourlyEntry.  # noqa: E501

        UV index value for the hour.  # noqa: E501

        :return: The uv_index of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._uv_index

    @uv_index.setter
    def uv_index(self, uv_index):
        """Sets the uv_index of this HourlyEntry.

        UV index value for the hour.  # noqa: E501

        :param uv_index: The uv_index of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._uv_index = uv_index

    @property
    def chanceofrain(self):
        """Gets the chanceofrain of this HourlyEntry.  # noqa: E501

        Chance of rain (percentage).  # noqa: E501

        :return: The chanceofrain of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceofrain

    @chanceofrain.setter
    def chanceofrain(self, chanceofrain):
        """Sets the chanceofrain of this HourlyEntry.

        Chance of rain (percentage).  # noqa: E501

        :param chanceofrain: The chanceofrain of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceofrain = chanceofrain

    @property
    def chanceofremdry(self):
        """Gets the chanceofremdry of this HourlyEntry.  # noqa: E501

        Chance of remaining dry (percentage).  # noqa: E501

        :return: The chanceofremdry of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceofremdry

    @chanceofremdry.setter
    def chanceofremdry(self, chanceofremdry):
        """Sets the chanceofremdry of this HourlyEntry.

        Chance of remaining dry (percentage).  # noqa: E501

        :param chanceofremdry: The chanceofremdry of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceofremdry = chanceofremdry

    @property
    def chanceofwindy(self):
        """Gets the chanceofwindy of this HourlyEntry.  # noqa: E501

        Chance of windy conditions (percentage).  # noqa: E501

        :return: The chanceofwindy of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceofwindy

    @chanceofwindy.setter
    def chanceofwindy(self, chanceofwindy):
        """Sets the chanceofwindy of this HourlyEntry.

        Chance of windy conditions (percentage).  # noqa: E501

        :param chanceofwindy: The chanceofwindy of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceofwindy = chanceofwindy

    @property
    def chanceofovercast(self):
        """Gets the chanceofovercast of this HourlyEntry.  # noqa: E501

        Chance of overcast skies (percentage).  # noqa: E501

        :return: The chanceofovercast of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceofovercast

    @chanceofovercast.setter
    def chanceofovercast(self, chanceofovercast):
        """Sets the chanceofovercast of this HourlyEntry.

        Chance of overcast skies (percentage).  # noqa: E501

        :param chanceofovercast: The chanceofovercast of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceofovercast = chanceofovercast

    @property
    def chanceofsunshine(self):
        """Gets the chanceofsunshine of this HourlyEntry.  # noqa: E501

        Chance of sunshine (percentage).  # noqa: E501

        :return: The chanceofsunshine of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceofsunshine

    @chanceofsunshine.setter
    def chanceofsunshine(self, chanceofsunshine):
        """Sets the chanceofsunshine of this HourlyEntry.

        Chance of sunshine (percentage).  # noqa: E501

        :param chanceofsunshine: The chanceofsunshine of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceofsunshine = chanceofsunshine

    @property
    def chanceoffrost(self):
        """Gets the chanceoffrost of this HourlyEntry.  # noqa: E501

        Chance of frost (percentage).  # noqa: E501

        :return: The chanceoffrost of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceoffrost

    @chanceoffrost.setter
    def chanceoffrost(self, chanceoffrost):
        """Sets the chanceoffrost of this HourlyEntry.

        Chance of frost (percentage).  # noqa: E501

        :param chanceoffrost: The chanceoffrost of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceoffrost = chanceoffrost

    @property
    def chanceofhightemp(self):
        """Gets the chanceofhightemp of this HourlyEntry.  # noqa: E501

        Chance of high temperature (percentage).  # noqa: E501

        :return: The chanceofhightemp of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceofhightemp

    @chanceofhightemp.setter
    def chanceofhightemp(self, chanceofhightemp):
        """Sets the chanceofhightemp of this HourlyEntry.

        Chance of high temperature (percentage).  # noqa: E501

        :param chanceofhightemp: The chanceofhightemp of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceofhightemp = chanceofhightemp

    @property
    def chanceoffog(self):
        """Gets the chanceoffog of this HourlyEntry.  # noqa: E501

        Chance of fog (percentage).  # noqa: E501

        :return: The chanceoffog of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceoffog

    @chanceoffog.setter
    def chanceoffog(self, chanceoffog):
        """Sets the chanceoffog of this HourlyEntry.

        Chance of fog (percentage).  # noqa: E501

        :param chanceoffog: The chanceoffog of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceoffog = chanceoffog

    @property
    def chanceofsnow(self):
        """Gets the chanceofsnow of this HourlyEntry.  # noqa: E501

        Chance of snow (percentage).  # noqa: E501

        :return: The chanceofsnow of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceofsnow

    @chanceofsnow.setter
    def chanceofsnow(self, chanceofsnow):
        """Sets the chanceofsnow of this HourlyEntry.

        Chance of snow (percentage).  # noqa: E501

        :param chanceofsnow: The chanceofsnow of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceofsnow = chanceofsnow

    @property
    def chanceofthunder(self):
        """Gets the chanceofthunder of this HourlyEntry.  # noqa: E501

        Chance of thunder (percentage).  # noqa: E501

        :return: The chanceofthunder of this HourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._chanceofthunder

    @chanceofthunder.setter
    def chanceofthunder(self, chanceofthunder):
        """Sets the chanceofthunder of this HourlyEntry.

        Chance of thunder (percentage).  # noqa: E501

        :param chanceofthunder: The chanceofthunder of this HourlyEntry.  # noqa: E501
        :type: object
        """

        self._chanceofthunder = chanceofthunder

    @property
    def air_quality(self):
        """Gets the air_quality of this HourlyEntry.  # noqa: E501


        :return: The air_quality of this HourlyEntry.  # noqa: E501
        :rtype: HourlyEntryAirQuality
        """
        return self._air_quality

    @air_quality.setter
    def air_quality(self, air_quality):
        """Sets the air_quality of this HourlyEntry.


        :param air_quality: The air_quality of this HourlyEntry.  # noqa: E501
        :type: HourlyEntryAirQuality
        """

        self._air_quality = air_quality

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HourlyEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HourlyEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
