# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request': 'ForecastResponseRequest',
        'location': 'CurrentWeatherResponseLocation',
        'current': 'ForecastResponseCurrent'
    }

    attribute_map = {
        'request': 'request',
        'location': 'location',
        'current': 'current'
    }

    def __init__(self, request=None, location=None, current=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501
        self._request = None
        self._location = None
        self._current = None
        self.discriminator = None
        if request is not None:
            self.request = request
        if location is not None:
            self.location = location
        if current is not None:
            self.current = current

    @property
    def request(self):
        """Gets the request of this InlineResponse200.  # noqa: E501


        :return: The request of this InlineResponse200.  # noqa: E501
        :rtype: ForecastResponseRequest
        """
        return self._request

    @request.setter
    def request(self, request):
        """Sets the request of this InlineResponse200.


        :param request: The request of this InlineResponse200.  # noqa: E501
        :type: ForecastResponseRequest
        """

        self._request = request

    @property
    def location(self):
        """Gets the location of this InlineResponse200.  # noqa: E501


        :return: The location of this InlineResponse200.  # noqa: E501
        :rtype: CurrentWeatherResponseLocation
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this InlineResponse200.


        :param location: The location of this InlineResponse200.  # noqa: E501
        :type: CurrentWeatherResponseLocation
        """

        self._location = location

    @property
    def current(self):
        """Gets the current of this InlineResponse200.  # noqa: E501


        :return: The current of this InlineResponse200.  # noqa: E501
        :rtype: ForecastResponseCurrent
        """
        return self._current

    @current.setter
    def current(self, current):
        """Sets the current of this InlineResponse200.


        :param current: The current of this InlineResponse200.  # noqa: E501
        :type: ForecastResponseCurrent
        """

        self._current = current

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
