# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse4XX(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'object',
        'error': 'ErrorResponseError'
    }

    attribute_map = {
        'success': 'success',
        'error': 'error'
    }

    def __init__(self, success=None, error=None):  # noqa: E501
        """InlineResponse4XX - a model defined in Swagger"""  # noqa: E501
        self._success = None
        self._error = None
        self.discriminator = None
        if success is not None:
            self.success = success
        if error is not None:
            self.error = error

    @property
    def success(self):
        """Gets the success of this InlineResponse4XX.  # noqa: E501

        Indicates whether the request succeeded.  # noqa: E501

        :return: The success of this InlineResponse4XX.  # noqa: E501
        :rtype: object
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this InlineResponse4XX.

        Indicates whether the request succeeded.  # noqa: E501

        :param success: The success of this InlineResponse4XX.  # noqa: E501
        :type: object
        """

        self._success = success

    @property
    def error(self):
        """Gets the error of this InlineResponse4XX.  # noqa: E501


        :return: The error of this InlineResponse4XX.  # noqa: E501
        :rtype: ErrorResponseError
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this InlineResponse4XX.


        :param error: The error of this InlineResponse4XX.  # noqa: E501
        :type: ErrorResponseError
        """

        self._error = error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse4XX, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse4XX):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
