# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MarineTideEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tide_time': 'object',
        'tide_height_mt': 'object',
        'tide_date_time': 'object',
        'tide_type': 'object'
    }

    attribute_map = {
        'tide_time': 'tideTime',
        'tide_height_mt': 'tideHeight_mt',
        'tide_date_time': 'tideDateTime',
        'tide_type': 'tide_type'
    }

    def __init__(self, tide_time=None, tide_height_mt=None, tide_date_time=None, tide_type=None):  # noqa: E501
        """MarineTideEntry - a model defined in Swagger"""  # noqa: E501
        self._tide_time = None
        self._tide_height_mt = None
        self._tide_date_time = None
        self._tide_type = None
        self.discriminator = None
        if tide_time is not None:
            self.tide_time = tide_time
        if tide_height_mt is not None:
            self.tide_height_mt = tide_height_mt
        if tide_date_time is not None:
            self.tide_date_time = tide_date_time
        if tide_type is not None:
            self.tide_type = tide_type

    @property
    def tide_time(self):
        """Gets the tide_time of this MarineTideEntry.  # noqa: E501

        Time of the tide event.  # noqa: E501

        :return: The tide_time of this MarineTideEntry.  # noqa: E501
        :rtype: object
        """
        return self._tide_time

    @tide_time.setter
    def tide_time(self, tide_time):
        """Sets the tide_time of this MarineTideEntry.

        Time of the tide event.  # noqa: E501

        :param tide_time: The tide_time of this MarineTideEntry.  # noqa: E501
        :type: object
        """

        self._tide_time = tide_time

    @property
    def tide_height_mt(self):
        """Gets the tide_height_mt of this MarineTideEntry.  # noqa: E501

        Height of the tide in meters.  # noqa: E501

        :return: The tide_height_mt of this MarineTideEntry.  # noqa: E501
        :rtype: object
        """
        return self._tide_height_mt

    @tide_height_mt.setter
    def tide_height_mt(self, tide_height_mt):
        """Sets the tide_height_mt of this MarineTideEntry.

        Height of the tide in meters.  # noqa: E501

        :param tide_height_mt: The tide_height_mt of this MarineTideEntry.  # noqa: E501
        :type: object
        """

        self._tide_height_mt = tide_height_mt

    @property
    def tide_date_time(self):
        """Gets the tide_date_time of this MarineTideEntry.  # noqa: E501

        Date and time of the tide event.  # noqa: E501

        :return: The tide_date_time of this MarineTideEntry.  # noqa: E501
        :rtype: object
        """
        return self._tide_date_time

    @tide_date_time.setter
    def tide_date_time(self, tide_date_time):
        """Sets the tide_date_time of this MarineTideEntry.

        Date and time of the tide event.  # noqa: E501

        :param tide_date_time: The tide_date_time of this MarineTideEntry.  # noqa: E501
        :type: object
        """

        self._tide_date_time = tide_date_time

    @property
    def tide_type(self):
        """Gets the tide_type of this MarineTideEntry.  # noqa: E501

        Type of tide event (HIGH or LOW).  # noqa: E501

        :return: The tide_type of this MarineTideEntry.  # noqa: E501
        :rtype: object
        """
        return self._tide_type

    @tide_type.setter
    def tide_type(self, tide_type):
        """Sets the tide_type of this MarineTideEntry.

        Type of tide event (HIGH or LOW).  # noqa: E501

        :param tide_type: The tide_type of this MarineTideEntry.  # noqa: E501
        :type: object
        """

        self._tide_type = tide_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MarineTideEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarineTideEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
