# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MarineForecastDay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'object',
        'date_epoch': 'object',
        'astro': 'ForecastDayAstro',
        'mintemp': 'object',
        'maxtemp': 'object',
        'avgtemp': 'object',
        'tides': 'object',
        'uv_index': 'object',
        'hourly': 'object'
    }

    attribute_map = {
        '_date': 'date',
        'date_epoch': 'date_epoch',
        'astro': 'astro',
        'mintemp': 'mintemp',
        'maxtemp': 'maxtemp',
        'avgtemp': 'avgtemp',
        'tides': 'tides',
        'uv_index': 'uv_index',
        'hourly': 'hourly'
    }

    def __init__(self, _date=None, date_epoch=None, astro=None, mintemp=None, maxtemp=None, avgtemp=None, tides=None, uv_index=None, hourly=None):  # noqa: E501
        """MarineForecastDay - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._date_epoch = None
        self._astro = None
        self._mintemp = None
        self._maxtemp = None
        self._avgtemp = None
        self._tides = None
        self._uv_index = None
        self._hourly = None
        self.discriminator = None
        if _date is not None:
            self._date = _date
        if date_epoch is not None:
            self.date_epoch = date_epoch
        if astro is not None:
            self.astro = astro
        if mintemp is not None:
            self.mintemp = mintemp
        if maxtemp is not None:
            self.maxtemp = maxtemp
        if avgtemp is not None:
            self.avgtemp = avgtemp
        if tides is not None:
            self.tides = tides
        if uv_index is not None:
            self.uv_index = uv_index
        if hourly is not None:
            self.hourly = hourly

    @property
    def _date(self):
        """Gets the _date of this MarineForecastDay.  # noqa: E501

        Forecast date (YYYY-MM-DD).  # noqa: E501

        :return: The _date of this MarineForecastDay.  # noqa: E501
        :rtype: object
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this MarineForecastDay.

        Forecast date (YYYY-MM-DD).  # noqa: E501

        :param _date: The _date of this MarineForecastDay.  # noqa: E501
        :type: object
        """

        self.__date = _date

    @property
    def date_epoch(self):
        """Gets the date_epoch of this MarineForecastDay.  # noqa: E501

        Forecast date as Unix epoch seconds.  # noqa: E501

        :return: The date_epoch of this MarineForecastDay.  # noqa: E501
        :rtype: object
        """
        return self._date_epoch

    @date_epoch.setter
    def date_epoch(self, date_epoch):
        """Sets the date_epoch of this MarineForecastDay.

        Forecast date as Unix epoch seconds.  # noqa: E501

        :param date_epoch: The date_epoch of this MarineForecastDay.  # noqa: E501
        :type: object
        """

        self._date_epoch = date_epoch

    @property
    def astro(self):
        """Gets the astro of this MarineForecastDay.  # noqa: E501


        :return: The astro of this MarineForecastDay.  # noqa: E501
        :rtype: ForecastDayAstro
        """
        return self._astro

    @astro.setter
    def astro(self, astro):
        """Sets the astro of this MarineForecastDay.


        :param astro: The astro of this MarineForecastDay.  # noqa: E501
        :type: ForecastDayAstro
        """

        self._astro = astro

    @property
    def mintemp(self):
        """Gets the mintemp of this MarineForecastDay.  # noqa: E501

        Minimum air temperature for the day.  # noqa: E501

        :return: The mintemp of this MarineForecastDay.  # noqa: E501
        :rtype: object
        """
        return self._mintemp

    @mintemp.setter
    def mintemp(self, mintemp):
        """Sets the mintemp of this MarineForecastDay.

        Minimum air temperature for the day.  # noqa: E501

        :param mintemp: The mintemp of this MarineForecastDay.  # noqa: E501
        :type: object
        """

        self._mintemp = mintemp

    @property
    def maxtemp(self):
        """Gets the maxtemp of this MarineForecastDay.  # noqa: E501

        Maximum air temperature for the day.  # noqa: E501

        :return: The maxtemp of this MarineForecastDay.  # noqa: E501
        :rtype: object
        """
        return self._maxtemp

    @maxtemp.setter
    def maxtemp(self, maxtemp):
        """Sets the maxtemp of this MarineForecastDay.

        Maximum air temperature for the day.  # noqa: E501

        :param maxtemp: The maxtemp of this MarineForecastDay.  # noqa: E501
        :type: object
        """

        self._maxtemp = maxtemp

    @property
    def avgtemp(self):
        """Gets the avgtemp of this MarineForecastDay.  # noqa: E501

        Average air temperature for the day.  # noqa: E501

        :return: The avgtemp of this MarineForecastDay.  # noqa: E501
        :rtype: object
        """
        return self._avgtemp

    @avgtemp.setter
    def avgtemp(self, avgtemp):
        """Sets the avgtemp of this MarineForecastDay.

        Average air temperature for the day.  # noqa: E501

        :param avgtemp: The avgtemp of this MarineForecastDay.  # noqa: E501
        :type: object
        """

        self._avgtemp = avgtemp

    @property
    def tides(self):
        """Gets the tides of this MarineForecastDay.  # noqa: E501

        Tidal events for the forecast day.  # noqa: E501

        :return: The tides of this MarineForecastDay.  # noqa: E501
        :rtype: object
        """
        return self._tides

    @tides.setter
    def tides(self, tides):
        """Sets the tides of this MarineForecastDay.

        Tidal events for the forecast day.  # noqa: E501

        :param tides: The tides of this MarineForecastDay.  # noqa: E501
        :type: object
        """

        self._tides = tides

    @property
    def uv_index(self):
        """Gets the uv_index of this MarineForecastDay.  # noqa: E501

        UV index for the day.  # noqa: E501

        :return: The uv_index of this MarineForecastDay.  # noqa: E501
        :rtype: object
        """
        return self._uv_index

    @uv_index.setter
    def uv_index(self, uv_index):
        """Sets the uv_index of this MarineForecastDay.

        UV index for the day.  # noqa: E501

        :param uv_index: The uv_index of this MarineForecastDay.  # noqa: E501
        :type: object
        """

        self._uv_index = uv_index

    @property
    def hourly(self):
        """Gets the hourly of this MarineForecastDay.  # noqa: E501

        Hourly marine weather forecast entries for the day.  # noqa: E501

        :return: The hourly of this MarineForecastDay.  # noqa: E501
        :rtype: object
        """
        return self._hourly

    @hourly.setter
    def hourly(self, hourly):
        """Sets the hourly of this MarineForecastDay.

        Hourly marine weather forecast entries for the day.  # noqa: E501

        :param hourly: The hourly of this MarineForecastDay.  # noqa: E501
        :type: object
        """

        self._hourly = hourly

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MarineForecastDay, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarineForecastDay):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
