# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MarineHourlyEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'object',
        'temperature': 'object',
        'wind_speed': 'object',
        'wind_degree': 'object',
        'wind_dir': 'object',
        'weather_code': 'object',
        'weather_icons': 'object',
        'weather_descriptions': 'object',
        'precip': 'object',
        'humidity': 'object',
        'visibility': 'object',
        'pressure': 'object',
        'cloudcover': 'object',
        'heatindex': 'object',
        'dewpoint': 'object',
        'windchill': 'object',
        'windgust': 'object',
        'feelslike': 'object',
        'sig_height_m': 'object',
        'swell_height': 'object',
        'swell_dir': 'object',
        'swell_dir_16_point': 'object',
        'swell_period_secs': 'object',
        'water_temp': 'object',
        'uv_index': 'object'
    }

    attribute_map = {
        'time': 'time',
        'temperature': 'temperature',
        'wind_speed': 'wind_speed',
        'wind_degree': 'wind_degree',
        'wind_dir': 'wind_dir',
        'weather_code': 'weather_code',
        'weather_icons': 'weather_icons',
        'weather_descriptions': 'weather_descriptions',
        'precip': 'precip',
        'humidity': 'humidity',
        'visibility': 'visibility',
        'pressure': 'pressure',
        'cloudcover': 'cloudcover',
        'heatindex': 'heatindex',
        'dewpoint': 'dewpoint',
        'windchill': 'windchill',
        'windgust': 'windgust',
        'feelslike': 'feelslike',
        'sig_height_m': 'sig_height_m',
        'swell_height': 'swell_height',
        'swell_dir': 'swell_dir',
        'swell_dir_16_point': 'swell_dir_16_point',
        'swell_period_secs': 'swell_period_secs',
        'water_temp': 'water_temp',
        'uv_index': 'uv_index'
    }

    def __init__(self, time=None, temperature=None, wind_speed=None, wind_degree=None, wind_dir=None, weather_code=None, weather_icons=None, weather_descriptions=None, precip=None, humidity=None, visibility=None, pressure=None, cloudcover=None, heatindex=None, dewpoint=None, windchill=None, windgust=None, feelslike=None, sig_height_m=None, swell_height=None, swell_dir=None, swell_dir_16_point=None, swell_period_secs=None, water_temp=None, uv_index=None):  # noqa: E501
        """MarineHourlyEntry - a model defined in Swagger"""  # noqa: E501
        self._time = None
        self._temperature = None
        self._wind_speed = None
        self._wind_degree = None
        self._wind_dir = None
        self._weather_code = None
        self._weather_icons = None
        self._weather_descriptions = None
        self._precip = None
        self._humidity = None
        self._visibility = None
        self._pressure = None
        self._cloudcover = None
        self._heatindex = None
        self._dewpoint = None
        self._windchill = None
        self._windgust = None
        self._feelslike = None
        self._sig_height_m = None
        self._swell_height = None
        self._swell_dir = None
        self._swell_dir_16_point = None
        self._swell_period_secs = None
        self._water_temp = None
        self._uv_index = None
        self.discriminator = None
        if time is not None:
            self.time = time
        if temperature is not None:
            self.temperature = temperature
        if wind_speed is not None:
            self.wind_speed = wind_speed
        if wind_degree is not None:
            self.wind_degree = wind_degree
        if wind_dir is not None:
            self.wind_dir = wind_dir
        if weather_code is not None:
            self.weather_code = weather_code
        if weather_icons is not None:
            self.weather_icons = weather_icons
        if weather_descriptions is not None:
            self.weather_descriptions = weather_descriptions
        if precip is not None:
            self.precip = precip
        if humidity is not None:
            self.humidity = humidity
        if visibility is not None:
            self.visibility = visibility
        if pressure is not None:
            self.pressure = pressure
        if cloudcover is not None:
            self.cloudcover = cloudcover
        if heatindex is not None:
            self.heatindex = heatindex
        if dewpoint is not None:
            self.dewpoint = dewpoint
        if windchill is not None:
            self.windchill = windchill
        if windgust is not None:
            self.windgust = windgust
        if feelslike is not None:
            self.feelslike = feelslike
        if sig_height_m is not None:
            self.sig_height_m = sig_height_m
        if swell_height is not None:
            self.swell_height = swell_height
        if swell_dir is not None:
            self.swell_dir = swell_dir
        if swell_dir_16_point is not None:
            self.swell_dir_16_point = swell_dir_16_point
        if swell_period_secs is not None:
            self.swell_period_secs = swell_period_secs
        if water_temp is not None:
            self.water_temp = water_temp
        if uv_index is not None:
            self.uv_index = uv_index

    @property
    def time(self):
        """Gets the time of this MarineHourlyEntry.  # noqa: E501

        Time in 24h format (e.g. '0900' for 09:00).  # noqa: E501

        :return: The time of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this MarineHourlyEntry.

        Time in 24h format (e.g. '0900' for 09:00).  # noqa: E501

        :param time: The time of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._time = time

    @property
    def temperature(self):
        """Gets the temperature of this MarineHourlyEntry.  # noqa: E501

        Air temperature at the given hour.  # noqa: E501

        :return: The temperature of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this MarineHourlyEntry.

        Air temperature at the given hour.  # noqa: E501

        :param temperature: The temperature of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._temperature = temperature

    @property
    def wind_speed(self):
        """Gets the wind_speed of this MarineHourlyEntry.  # noqa: E501

        Wind speed at the given hour.  # noqa: E501

        :return: The wind_speed of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._wind_speed

    @wind_speed.setter
    def wind_speed(self, wind_speed):
        """Sets the wind_speed of this MarineHourlyEntry.

        Wind speed at the given hour.  # noqa: E501

        :param wind_speed: The wind_speed of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._wind_speed = wind_speed

    @property
    def wind_degree(self):
        """Gets the wind_degree of this MarineHourlyEntry.  # noqa: E501

        Wind direction in degrees.  # noqa: E501

        :return: The wind_degree of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._wind_degree

    @wind_degree.setter
    def wind_degree(self, wind_degree):
        """Sets the wind_degree of this MarineHourlyEntry.

        Wind direction in degrees.  # noqa: E501

        :param wind_degree: The wind_degree of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._wind_degree = wind_degree

    @property
    def wind_dir(self):
        """Gets the wind_dir of this MarineHourlyEntry.  # noqa: E501

        Wind direction as a compass point.  # noqa: E501

        :return: The wind_dir of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._wind_dir

    @wind_dir.setter
    def wind_dir(self, wind_dir):
        """Sets the wind_dir of this MarineHourlyEntry.

        Wind direction as a compass point.  # noqa: E501

        :param wind_dir: The wind_dir of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._wind_dir = wind_dir

    @property
    def weather_code(self):
        """Gets the weather_code of this MarineHourlyEntry.  # noqa: E501

        Weather condition code for the hour.  # noqa: E501

        :return: The weather_code of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._weather_code

    @weather_code.setter
    def weather_code(self, weather_code):
        """Sets the weather_code of this MarineHourlyEntry.

        Weather condition code for the hour.  # noqa: E501

        :param weather_code: The weather_code of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._weather_code = weather_code

    @property
    def weather_icons(self):
        """Gets the weather_icons of this MarineHourlyEntry.  # noqa: E501

        Array of icon URLs representing the weather.  # noqa: E501

        :return: The weather_icons of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._weather_icons

    @weather_icons.setter
    def weather_icons(self, weather_icons):
        """Sets the weather_icons of this MarineHourlyEntry.

        Array of icon URLs representing the weather.  # noqa: E501

        :param weather_icons: The weather_icons of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._weather_icons = weather_icons

    @property
    def weather_descriptions(self):
        """Gets the weather_descriptions of this MarineHourlyEntry.  # noqa: E501

        Array of text descriptions of the weather.  # noqa: E501

        :return: The weather_descriptions of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._weather_descriptions

    @weather_descriptions.setter
    def weather_descriptions(self, weather_descriptions):
        """Sets the weather_descriptions of this MarineHourlyEntry.

        Array of text descriptions of the weather.  # noqa: E501

        :param weather_descriptions: The weather_descriptions of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._weather_descriptions = weather_descriptions

    @property
    def precip(self):
        """Gets the precip of this MarineHourlyEntry.  # noqa: E501

        Precipitation amount for the hour.  # noqa: E501

        :return: The precip of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._precip

    @precip.setter
    def precip(self, precip):
        """Sets the precip of this MarineHourlyEntry.

        Precipitation amount for the hour.  # noqa: E501

        :param precip: The precip of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._precip = precip

    @property
    def humidity(self):
        """Gets the humidity of this MarineHourlyEntry.  # noqa: E501

        Relative humidity percentage.  # noqa: E501

        :return: The humidity of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity):
        """Sets the humidity of this MarineHourlyEntry.

        Relative humidity percentage.  # noqa: E501

        :param humidity: The humidity of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._humidity = humidity

    @property
    def visibility(self):
        """Gets the visibility of this MarineHourlyEntry.  # noqa: E501

        Visibility distance for the hour.  # noqa: E501

        :return: The visibility of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility):
        """Sets the visibility of this MarineHourlyEntry.

        Visibility distance for the hour.  # noqa: E501

        :param visibility: The visibility of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._visibility = visibility

    @property
    def pressure(self):
        """Gets the pressure of this MarineHourlyEntry.  # noqa: E501

        Atmospheric pressure for the hour.  # noqa: E501

        :return: The pressure of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._pressure

    @pressure.setter
    def pressure(self, pressure):
        """Sets the pressure of this MarineHourlyEntry.

        Atmospheric pressure for the hour.  # noqa: E501

        :param pressure: The pressure of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._pressure = pressure

    @property
    def cloudcover(self):
        """Gets the cloudcover of this MarineHourlyEntry.  # noqa: E501

        Cloud cover percentage.  # noqa: E501

        :return: The cloudcover of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._cloudcover

    @cloudcover.setter
    def cloudcover(self, cloudcover):
        """Sets the cloudcover of this MarineHourlyEntry.

        Cloud cover percentage.  # noqa: E501

        :param cloudcover: The cloudcover of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._cloudcover = cloudcover

    @property
    def heatindex(self):
        """Gets the heatindex of this MarineHourlyEntry.  # noqa: E501

        Heat index value for the hour.  # noqa: E501

        :return: The heatindex of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._heatindex

    @heatindex.setter
    def heatindex(self, heatindex):
        """Sets the heatindex of this MarineHourlyEntry.

        Heat index value for the hour.  # noqa: E501

        :param heatindex: The heatindex of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._heatindex = heatindex

    @property
    def dewpoint(self):
        """Gets the dewpoint of this MarineHourlyEntry.  # noqa: E501

        Dew point temperature for the hour.  # noqa: E501

        :return: The dewpoint of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._dewpoint

    @dewpoint.setter
    def dewpoint(self, dewpoint):
        """Sets the dewpoint of this MarineHourlyEntry.

        Dew point temperature for the hour.  # noqa: E501

        :param dewpoint: The dewpoint of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._dewpoint = dewpoint

    @property
    def windchill(self):
        """Gets the windchill of this MarineHourlyEntry.  # noqa: E501

        Wind chill temperature for the hour.  # noqa: E501

        :return: The windchill of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._windchill

    @windchill.setter
    def windchill(self, windchill):
        """Sets the windchill of this MarineHourlyEntry.

        Wind chill temperature for the hour.  # noqa: E501

        :param windchill: The windchill of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._windchill = windchill

    @property
    def windgust(self):
        """Gets the windgust of this MarineHourlyEntry.  # noqa: E501

        Wind gust speed for the hour.  # noqa: E501

        :return: The windgust of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._windgust

    @windgust.setter
    def windgust(self, windgust):
        """Sets the windgust of this MarineHourlyEntry.

        Wind gust speed for the hour.  # noqa: E501

        :param windgust: The windgust of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._windgust = windgust

    @property
    def feelslike(self):
        """Gets the feelslike of this MarineHourlyEntry.  # noqa: E501

        Apparent temperature (feels like) for the hour.  # noqa: E501

        :return: The feelslike of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._feelslike

    @feelslike.setter
    def feelslike(self, feelslike):
        """Sets the feelslike of this MarineHourlyEntry.

        Apparent temperature (feels like) for the hour.  # noqa: E501

        :param feelslike: The feelslike of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._feelslike = feelslike

    @property
    def sig_height_m(self):
        """Gets the sig_height_m of this MarineHourlyEntry.  # noqa: E501

        Significant wave height in meters.  # noqa: E501

        :return: The sig_height_m of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._sig_height_m

    @sig_height_m.setter
    def sig_height_m(self, sig_height_m):
        """Sets the sig_height_m of this MarineHourlyEntry.

        Significant wave height in meters.  # noqa: E501

        :param sig_height_m: The sig_height_m of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._sig_height_m = sig_height_m

    @property
    def swell_height(self):
        """Gets the swell_height of this MarineHourlyEntry.  # noqa: E501

        Swell height in meters.  # noqa: E501

        :return: The swell_height of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._swell_height

    @swell_height.setter
    def swell_height(self, swell_height):
        """Sets the swell_height of this MarineHourlyEntry.

        Swell height in meters.  # noqa: E501

        :param swell_height: The swell_height of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._swell_height = swell_height

    @property
    def swell_dir(self):
        """Gets the swell_dir of this MarineHourlyEntry.  # noqa: E501

        Swell direction in degrees.  # noqa: E501

        :return: The swell_dir of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._swell_dir

    @swell_dir.setter
    def swell_dir(self, swell_dir):
        """Sets the swell_dir of this MarineHourlyEntry.

        Swell direction in degrees.  # noqa: E501

        :param swell_dir: The swell_dir of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._swell_dir = swell_dir

    @property
    def swell_dir_16_point(self):
        """Gets the swell_dir_16_point of this MarineHourlyEntry.  # noqa: E501

        Swell direction as a 16-point compass.  # noqa: E501

        :return: The swell_dir_16_point of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._swell_dir_16_point

    @swell_dir_16_point.setter
    def swell_dir_16_point(self, swell_dir_16_point):
        """Sets the swell_dir_16_point of this MarineHourlyEntry.

        Swell direction as a 16-point compass.  # noqa: E501

        :param swell_dir_16_point: The swell_dir_16_point of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._swell_dir_16_point = swell_dir_16_point

    @property
    def swell_period_secs(self):
        """Gets the swell_period_secs of this MarineHourlyEntry.  # noqa: E501

        Swell period in seconds.  # noqa: E501

        :return: The swell_period_secs of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._swell_period_secs

    @swell_period_secs.setter
    def swell_period_secs(self, swell_period_secs):
        """Sets the swell_period_secs of this MarineHourlyEntry.

        Swell period in seconds.  # noqa: E501

        :param swell_period_secs: The swell_period_secs of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._swell_period_secs = swell_period_secs

    @property
    def water_temp(self):
        """Gets the water_temp of this MarineHourlyEntry.  # noqa: E501

        Sea surface temperature at the given hour.  # noqa: E501

        :return: The water_temp of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._water_temp

    @water_temp.setter
    def water_temp(self, water_temp):
        """Sets the water_temp of this MarineHourlyEntry.

        Sea surface temperature at the given hour.  # noqa: E501

        :param water_temp: The water_temp of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._water_temp = water_temp

    @property
    def uv_index(self):
        """Gets the uv_index of this MarineHourlyEntry.  # noqa: E501

        UV index value for the hour.  # noqa: E501

        :return: The uv_index of this MarineHourlyEntry.  # noqa: E501
        :rtype: object
        """
        return self._uv_index

    @uv_index.setter
    def uv_index(self, uv_index):
        """Sets the uv_index of this MarineHourlyEntry.

        UV index value for the hour.  # noqa: E501

        :param uv_index: The uv_index of this MarineHourlyEntry.  # noqa: E501
        :type: object
        """

        self._uv_index = uv_index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MarineHourlyEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarineHourlyEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
