# coding: utf-8

"""
    Weatherstack API

    The Weatherstack API was built to deliver accurate weather data for any application and use case, from real-time and historical weather information along with advances weather stats like Marine data all the way to 14-day weather forecasts, supporting all major programming languages. Our straightforward API design will make it easy to use the API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TideEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'object',
        'height': 'object',
        'type': 'object'
    }

    attribute_map = {
        'time': 'time',
        'height': 'height',
        'type': 'type'
    }

    def __init__(self, time=None, height=None, type=None):  # noqa: E501
        """TideEntry - a model defined in Swagger"""  # noqa: E501
        self._time = None
        self._height = None
        self._type = None
        self.discriminator = None
        if time is not None:
            self.time = time
        if height is not None:
            self.height = height
        if type is not None:
            self.type = type

    @property
    def time(self):
        """Gets the time of this TideEntry.  # noqa: E501

        Time of the tide event.  # noqa: E501

        :return: The time of this TideEntry.  # noqa: E501
        :rtype: object
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this TideEntry.

        Time of the tide event.  # noqa: E501

        :param time: The time of this TideEntry.  # noqa: E501
        :type: object
        """

        self._time = time

    @property
    def height(self):
        """Gets the height of this TideEntry.  # noqa: E501

        Height of the tide at the event.  # noqa: E501

        :return: The height of this TideEntry.  # noqa: E501
        :rtype: object
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this TideEntry.

        Height of the tide at the event.  # noqa: E501

        :param height: The height of this TideEntry.  # noqa: E501
        :type: object
        """

        self._height = height

    @property
    def type(self):
        """Gets the type of this TideEntry.  # noqa: E501

        Type of tide event (High, Low, or Normal).  # noqa: E501

        :return: The type of this TideEntry.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TideEntry.

        Type of tide event (High, Low, or Normal).  # noqa: E501

        :param type: The type of this TideEntry.  # noqa: E501
        :type: object
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TideEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TideEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
